### ISSUE TITLE
[Bug Report] 无法从 11.0.0 自动升级到 12.* 及更高版本

### ISSUE THREAD

**Issue by Gravifer** [robertying/learnX#1005]
从 11.0.0 升级至 12.* 及 13.0.0 版本时，新版本安装过程进行到约 90% 时发生闪退。
卸载 11.0.0 后，新版本的安装可以正常完成；原有用户信息似乎能够正常载入。

平台: Samsung Galaxy S9+ (SM-G9650)
系统: Android 10, security 2021-2-1

P.S.: 猜测与推送通知功能有关；建议在 11.0.0 的 Release Note 里进行说明即可。

**Comment by robertying** [comment]
安装时发生闪退吗？不是安装完成后闪退？

**Comment by Gravifer** [comment]
不是。闪退后仍为11.0.0，新版本没有安装上。

**Comment by Gravifer** [comment]
对12.*和13.0.0各个小版本都做了测试.
的确还是可能是我单机不可复现的问题；但由于我还需要日常使用，不计划回滚再进行更多测试。我认为你可以
A. 关闭本 issue，在 11.0.0 release note 中加入说明
B. 开放本 issue，若有人报告同样问题再进行 A
C. 关闭本 issue
考虑到或许大家都有在按时更新（不像我），三个选项在我看来都是可行的。
如果我这边在未来版本仍然遇到类似问题，我会在本 issue 下继续更新情况，并进一步调查可能你引发此问题的依赖和冲突。

**Comment by robertying** [comment]
安装时闪退，可能是系统不兼容。我会在模拟器上做一次测试。

**Comment by robertying** [comment]
我使用 Android 10 的模拟器安装了 v11.0.0，可以正常打开；再覆盖安装了 v13.0.0，可以继续正常打开。未出现安装中闪退问题，怀疑是系统问题。先 close 了。
