### ISSUE TITLE
公告有时显示不正常

### ISSUE THREAD

**Issue by AolinJian** [robertying/learnX#1006]
如题，公告有的时候不能显示出来，但是可以选中文字之后复制（复制时还是看不见）。估计是字体颜色问题？

**Comment by robertying** [comment]
请问无论在正常模式还是暗黑模式下，文字均没有显示吗？
其次，在网络学堂网页上，是否可以正常显示？

**Comment by AolinJian** [comment]
奇怪的是我在安卓平板上可以看的通知，手机上无论明亮模式还是黑暗模式都看不到字😂

**Comment by robertying** [comment]
电脑网页上可以看到吗？

**Comment by AolinJian** [comment]
网页版网络学堂可以。

**Comment by robertying** [comment]
通过手机的自带浏览器，访问网页版网络学堂，可以看到字吗？

**Comment by AolinJian** [comment]
手机浏览器看网络学堂通知没问题...

**Comment by robertying** [comment]
这样的话，要么通过联系我邮箱，私聊一下？

**Comment by robertying** [comment]
如果仍然有问题，请通过邮箱和我联系。这个 issue 由于长期未收到回复，将被暂时 close。
