### ISSUE TITLE
不重启应用无法刷新

### ISSUE THREAD

**Issue by liang2kl** [robertying/learnX#1007]
iOS版进入后台一段时间后，下拉刷新无效，且无法加载文件。强制关闭后进入无此问题。

**Comment by robertying** [comment]
请问 App 版本。

**Comment by liang2kl** [comment]
> 请问 App 版本。

13.0

**Comment by robertying** [comment]
我自己测试过，最新 v13.1.0 在后台一小时甚至半天，再进入刷新是没有问题的。

**Comment by liang2kl** [comment]
> 我自己测试过，最新 v13.1.0 在后台一小时甚至半天，再进入刷新是没有问题的。

抱歉，出现问题的设备版本是13.0.1，13.1.0应该已经修复这个问题：

> 修复了一个可能导致自动登录（登录状态保持）失效的问题。
