### ISSUE TITLE
Showing files in MacOS X does not work properly

### ISSUE THREAD

**Issue by tqyaaaaang** [robertying/learnX#1009]
After a recent major update (I guess is v12.1.0, where there were significant changes in the UI), showing files such as PDFs or PPTs, including course files and attachments in assignments, will not work properly. I can only view the file by sharing it to another application.

Some notes:
- Opening text files is okay
- The same feature works well in iOS

**Comment by robertying** [comment]
PDF 应该是 OK 的，PPT 由于 macOS 12 开始的 WebView 似乎不能正常渲染，因此被我主动屏蔽了预览。

目前只允许 PDF 和图片的预览功能，其他扩展名的都只支持通过分享打开文件。

PDF 不能预览的话，能否提供一下截图。

**Comment by tqyaaaaang** [comment]
It just get stuck at the following (I've already refreshed the file)
<img width="781" alt="image" src="https://user-images.githubusercontent.com/31098199/116136510-f9f19900-a704-11eb-8e95-0985fabe8f3a.png">

**Comment by tqyaaaaang** [comment]
BTW, I'm still at Catalina 10.15.7

**Comment by robertying** [comment]
两点：

1. 10.15 的系统判断有问题，导致 App 打开后展示的不是分栏界面。
2. 经测试，采用 macOS 11 SDK 编译的 App 在 10.15 上不能正确预览 PDF，可以正确预览图片。因为我手头没有 10.15 设备，因此下一个更新中会屏蔽 10.15 的 PDF 预览，而直接显示一个分享按钮。也就是 11 可预览 PDF+图片，10.15 仅可预览图片，其他格式不支持预览。
