### ISSUE TITLE
安卓版作业上传文件的文件名问题

### ISSUE THREAD

**Issue by mhliu0001** [robertying/learnX#1010]
设备华为matepad 10.8，版本v13.2.1
上传作业时，文件名中的中文字符会被删掉，比如上传高微2作业11.pdf，上传后显示文件名是211.pdf

**Comment by robertying** [comment]
在 v13.3.0 中修复。

测试能力有限，如果之后版本依旧存在问题，请重新 open 此 issue。

**Comment by mhliu0001** [comment]
v13.3.0中此问题仍然存在。

**Comment by mhliu0001** [comment]
是上传完以后，重新看这个作业以后，文件名的中文就消失了。上传页面不会出任何问题
