### ISSUE TITLE
v13.3.0作业附件中文文件名的问题仍然存在

### ISSUE THREAD

**Issue by mhliu0001** [robertying/learnX#1011]
#1010

**Comment by robertying** [comment]
这是由于 React Native 默认使用编译好的 aar 包，导致我的 patch 无法生效。

由于自己从源码编译比较复杂，这个问题可能要等待上游修复后，再解决。

**Comment by robertying** [comment]
使用包含修复代码的源代码重新编译了 React Native。请检查 v13.4.0 是否解决问题。如仍未解决，请 reopen issue。
