### ISSUE TITLE
连续3天无法同步日历

### ISSUE THREAD

**Issue by panda2134** [robertying/learnX#1012]
环境校园网，如果需要更多调试信息可以提供

测试环境：
- iPhone 8P, iOS 15.0 Beta
- iPad Air (4th Generation), iPadOS 14.5.1
- Macbook Pro 2019, MacOS 11.3.1

**Comment by robertying** [comment]
麻烦尝试以下步骤：

1. 登录网络学堂
2. 在同一个浏览器访问 https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20210611&p_end_date=20210711&jsoncallback=thu_learn_lib_jsonp_extractor
3. 查看返回结果
4. 建议在抹除敏感信息后，将返回结果附上，或者可以发到我的邮箱中。

**Comment by robertying** [comment]
没有反馈，先 close 了

**Comment by LinShan-Bin** [comment]
同样的问题，该链接返回

```
thu_learn_lib_jsonp_extractor([])
```

**Comment by robertying** [comment]
> 同样的问题，该链接返回
> 
> ```
> thu_learn_lib_jsonp_extractor([])
> ```

如果使用的是以上的链接，就是返回空。你需要更改 p_start_date 和 p_end_date 到最近的日期才能看到结果。

其次，请确保同步时连接到了校园网。
