### ISSUE TITLE
语言设置

### ISSUE THREAD

**Issue by function2-llx** [robertying/learnX#1016]
当前 app 似乎是检测系统语言自动设置语言，是否考虑改成由用户自行设定？

**Comment by robertying** [comment]
如果是 iOS 系统，可以进入系统设置，下拉到 learnX 设置，为 app 单独选择语言。

如果是 Android 系统，暂时没有加入这个功能的计划。

**Comment by function2-llx** [comment]
我是 Android 用户，因为一些原因系统语言是英文，英文在 app 中的显示时常会出现一些省略号（可能因为 UI 主要只对中文适配过），所以这个功能对我来说还是很有用的；不然，或许也可以考虑 UI 对英文适配更友好一些。

<img src="https://user-images.githubusercontent.com/38486514/133584104-0c3a52e1-b003-4115-ad73-8ba08fa179e5.png" width="50%"/>

**Comment by robertying** [comment]
请问屏幕的尺寸是多少？Android 这边测试本身就是英文下进行的，采用的是比较常见的 1080 宽度。这个可能是适配问题，如果有型号之类的信息，我可能可以修复。

**Comment by robertying** [comment]
ping 一下 @function2-llx，马上要发版本了。最好能够最近解决。

**Comment by function2-llx** [comment]
啊抱歉之前没回复上。

我的手机是小米9，屏幕尺寸是6.39英寸，分辨率是2340 x 1080。

**Comment by robertying** [comment]
模拟器上测试，UI 并没有问题。有没有可能是某些缩放或者字体设置的影响？是否是标准缩放和系统默认字体及字号？

**Comment by function2-llx** [comment]
我前天更新了 MIUI，然后就显示正常了。我之前没有调过缩放、字体字号之类的设置，可能是 MIUI 的问题吧。

**Comment by robertying** [comment]
那就先 close 了。
