### ISSUE TITLE
iOS 无法同步作业到reminders

### ISSUE THREAD

**Issue by weikang0519** [robertying/learnX#1017]
如图所示
![687FD13D-B156-49E7-AE56-6FEF99415D60](https://user-images.githubusercontent.com/90672952/134482884-e8855383-cadb-4331-bdb7-0b5400163317.png)
![465B9F4A-D973-4086-8FC5-C6DC56DA9D8F](https://user-images.githubusercontent.com/90672952/134482932-3d488be0-53d2-4c53-83b5-5823740de57a.png)

**Comment by robertying** [comment]
请问本身能否正常使用 Reminders？一般情况下，learnX 会找 iCloud 账户并建立一个 reminder，然后 fallback 到本地 reminder。这种报错说明，既不存在 iCloud 账户，也没有本地的 reminder 存在。

**Comment by weikang0519** [comment]
解决了，谢谢！
