### ISSUE TITLE
华为课表日程无法导出或同步到Outlook

### ISSUE THREAD

**Issue by silverpoetry** [robertying/learnX#1018]
生成的课表日历信息在系统自带的日历软件中显示为来自名叫“learnX课表”的账户，然而，不知道这些日程如何导出。此外，开启和Outlook自动同步功能时，该课表里的日程也不会同步到Outlook日程中。
如图
![Screenshot_20210924_143301_com android calendar](https://user-images.githubusercontent.com/11042077/134628948-87ab3f10-be5b-4eec-9553-5e5475ba3040.jpg)
希望能够增加课表文件导出活同步的功能。

**Comment by robertying** [comment]
同 https://github.com/robertying/learnX/issues/872，目前没有能力做到能够让第三方 app 同步此日历，因为本身数据源是 app 在本地手动写入的。如果需要同步，可以通过相同的 thu-learn-lib 获取日历，序列化，转换为 ics，再订阅。learnX 只提供本地服务，暂时没有考虑做任何在线服务。
