### ISSUE TITLE
作业同步到reminder的问题

### ISSUE THREAD

**Issue by Quinoline233** [robertying/learnX#1019]
当作业数量发生变化时（比如提交了一份作业），而后刷新同步时，learnx会重复的把其他未完成的作业再一次推送至reminder中。

**Comment by robertying** [comment]
最后结果是每个作业有两个提醒事项？
能否检查下 reminders 里面的 list 是否包含两个 learnX list？还是只有一个 list，里面有重复的 reminder。

**Comment by Quinoline233** [comment]
只有一个list 里面包含重复的reminder

**Comment by robertying** [comment]
将原有 reminder list 删除，再进行同步，再提交作业，再刷新同步，是否还会有重复的问题？

我这边不太好测试作业数量发生变化的情况。

**Comment by Quinoline233** [comment]
这样就没有重复的问题了
感谢
