### ISSUE TITLE
附件下载问题

### ISSUE THREAD

**Issue by Just-7-Fans** [robertying/learnX#1020]
RAR和ZIP文件经常出现下载失败的问题，是怎么回事呢？

**Comment by robertying** [comment]
请问软件版本是多少，是哪个系统以及系统版本。下载的文件大小是多少。

**Comment by Just-7-Fans** [comment]
软件版本：v13.7.1
ios系统，系统版本：15.0.1（19A348）
文件：ZIP 7K   RAR 2M   RAR 647K   ZIP 2M

**Comment by robertying** [comment]
请问是否在校园网下操作？

**Comment by Just-7-Fans** [comment]
是在校园网下操作的
清除文件缓存似乎无效

**Comment by robertying** [comment]
是否有错误提示？

iOS 本身不支持 rar 预览，需要在其他 app 内打开才行。

**Comment by Just-7-Fans** [comment]
是的，显示Failed to download the file.
嗯嗯，我用的是shu.
![28681823-BFAB-4753-9EDD-A394726F0113](https://user-images.githubusercontent.com/81455739/136019503-a1d3aa32-2ab3-4dac-a014-66f46c7bd38f.png)

**Comment by robertying** [comment]
长时间未回复，暂时 close。
