### ISSUE TITLE
calendar cannot be found

### ISSUE THREAD

**Issue by Xky-walker** [robertying/learnX#1024]
hello. My phone have upgraded to HarmonyOS 3.0. Then learnX cannot find the calendar to sync the homework. Appreciate it if you can fix it soon.

**Comment by robertying** [comment]
1. 是否尝试过“删除已同步日历”，然后重新同步？
2. 请检查是否给予了 learnX 读写日历的权限？

**Comment by Xky-walker** [comment]
在删除已同步的日历时也报错：calendar could not be found. 权限已经给了。-------- 原始邮件 --------发件人： Rui Ying ***@***.***>日期： 2022年8月31日周三 01:33收件人： robertying/learnX ***@***.***>抄送： xkywalker ***@***.***>, Author ***@***.***>主    题： Re: [robertying/learnX] calendar cannot be found (Issue #1024)

是否尝试过“删除已同步日历”，然后重新同步？请检查是否给予了 learnX 读写日历的权限？

**Comment by robertying** [comment]
尝试手动创建一个日历，名为 `learnX 作业`，然后再同步作业。

**Comment by robertying** [comment]
可否上传点击“删除已同步的日历”后出现错误的截图？

**Comment by hfsbjtfb** [comment]
![Screenshot_20220908_123205_io robertying learnx](https://user-images.githubusercontent.com/113083649/189035542-bbd64f5b-7e32-46f7-b87b-cff3bf9577b2.jpg)

**Comment by hfsbjtfb** [comment]
个人觉得应该是HarmonyOS 3.0的问题 刚用一台小米设备测试了一下 可以正常同步 但更新了HarmonyOS 3.0的手机和平板在进行同步和删除日历操作时都显示calendars could not be found

**Comment by robertying** [comment]
看了一下，这个错误的原因就是找不到 `com.android.calendar`。我手上没有华为设备，所以也没法根据这个问题专门研究解决办法（比如换成鸿蒙的 calendar 的包名）。
先 close 了。

**Comment by hfsbjtfb** [comment]
刚查看了一下calendar的包名 果然 HarmonyOS 3.0把包名改成了com.huawei.calendar
另 祝中秋快乐！

**Comment by Xky-walker** [comment]
谢谢，中秋快乐！

**Comment by robertying** [comment]
如果你们愿意帮我测试的话，我也可以尝试修复下。有了这个包名，可能会有帮助。

**Comment by YiHui-Liu** [comment]
> 刚查看了一下calendar的包名 果然 HarmonyOS 3.0把包名改成了com.huawei.calendar

请问有什么办法可以解决吗，还是说需要等待下一个release

**Comment by robertying** [comment]
获取日历的方式应该是通过系统主动提供的日历 provider，而鸿蒙没有暴露这个 provider，所以代码没有办法获取日历。
我怀疑因为国内人用日历的少，所以鸿蒙的这个 bug 没人反馈。
综上所述，这个问题的解决需要系统支持，我这边没有好的解决办法。

**Comment by hfsbjtfb** [comment]
谢谢您 已经反馈了相关问题
(另外 我在HarmonyOS官网找到了一些相关文档 不过我也不太懂 不知道有没有帮助 https://developer.harmonyos.com/cn/docs/documentation/doc-references/js-service-widget-basic-calendar-0000001106228838

**Comment by robertying** [comment]
这个是用来显示日历 UI 组件的，和我们需要的 Android 日历 provider 不一样。

**Comment by robertying** [comment]
@YiHui-Liu @Xky-walker @hfsbjtfb 几位如果有空的话，可否帮忙测试一下这个版本。只是修改了日历包名，没有改其他的日历相关属性，如果鸿蒙把其他属性也改了的话，可能还是会失败。
[harmonyos-fix-test.zip](https://github.com/robertying/learnX/files/9553810/harmonyos-fix-test.zip)

**Comment by YiHui-Liu** [comment]
> @YiHui-Liu @Xky-walker @hfsbjtfb 几位如果有空的话，可否帮忙测试一下这个版本。只是修改了日历包名，没有改其他的日历相关属性，如果鸿蒙把其他属性也改了的话，可能还是会失败。
> 
> APK: [harmonyos-fix-test.zip](https://github.com/robertying/learnX/files/9553810/harmonyos-fix-test.zip)

![834731f7221a3f1ec1b01f9b517aa1f](https://user-images.githubusercontent.com/30190271/189824056-841b5200-e4a3-42e7-a53e-0a9db90ba2ec.jpg)
能够提示给予权限，但是依然无法同步，选择删除同样提示：``

> ![Screenshot_20220908_123205_io robertying learnx](https://user-images.githubusercontent.com/113083649/189035542-bbd64f5b-7e32-46f7-b87b-cff3bf9577b2.jpg)

**Comment by hfsbjtfb** [comment]
我这边也还是显示calendars could not be found
不过还是辛苦啦 谢谢!

**Comment by robertying** [comment]
如果安装一个日历程序，比如 Outlook，然后还是安装回*之前的普通版本*，能否尝试下？

**Comment by hfsbjtfb** [comment]
弄到了旧版的日历安装包 但是Harmony OS 3.0无法安装旧版的日历
然后我找到了 这两个https://developer.harmonyos.com/cn/docs/documentation/doc-references/overview-0000001060268801
https://developer.huawei.com/consumer/cn/forum/topic/0202980366533670095?fid=0102683795438680754
不知道是否有帮助 
还是说声谢谢 辛苦您了

> 如果安装一个日历程序，比如 Outlook，然后还是安装回_之前的普通版本_，能否尝试下？

**Comment by robertying** [comment]
@hfsbjtfb 第二个链接应该非常有用！感谢！
具体说的是 Android 11 开始的 package visibility：https://developer.android.com/training/package-visibility

**Comment by robertying** [comment]
Fixed via 9df4dfbb031941fc41ba70a8753e0ecfd23861af
请下载最新 release 验证问题是否解决。

**Comment by hfsbjtfb** [comment]
> Fixed via [9df4dfb](https://github.com/robertying/learnX/commit/9df4dfbb031941fc41ba70a8753e0ecfd23861af) 请下载最新 release 验证问题是否解决。

您好 问题已经解决了 非常感谢!

**Comment by Xky-walker** [comment]
已经解决，谢谢！

**Comment by YiHui-Liu** [comment]
> > Fixed via [9df4dfb](https://github.com/robertying/learnX/commit/9df4dfbb031941fc41ba70a8753e0ecfd23861af) 请下载最新 release 验证问题是否解决。
> 
> 您好 问题已经解决了 非常感谢!

请问你的系统版本是什么，我现在是HMOS 3.0.0.117，还是不能同步日历

**Comment by hfsbjtfb** [comment]
> 

我两台设备都是3.0.0.116 都可以同步

**Comment by YiHui-Liu** [comment]
> 

好的，谢谢，我再尝试一下

**Comment by Xky-walker** [comment]
也还是不行。calendar could not be found.-------- 原始邮件 --------发件人： Rui Ying ***@***.***>日期： 2022年8月31日周三 12:45收件人： robertying/learnX ***@***.***>抄送： xkywalker ***@***.***>, Author ***@***.***>主    题： Re: [robertying/learnX] calendar cannot be found (Issue #1024)

尝试手动创建一个日历，名为 learnX 作业，然后再同步作业。

**Comment by robertying** [comment]
@Xky-walker 请安装GitHub上最新的版本，版本号没变，但是最新版本才带 fix。

**Comment by Xky-walker** [comment]
Love from your friend!
