### ISSUE TITLE
Can't add calendar to iPhone

### ISSUE THREAD

**Issue by Ageha-Xia** [robertying/learnX#1025]
我的手机中已经有了一个learnX的日历，但在learnX中点同步课表并不能将新学期的日历同步过来。

**Comment by robertying** [comment]
“删除已同步日历”然后重新同步呢？

**Comment by Ageha-Xia** [comment]
“删除已同步日历”再“同步课表”依然不能同步日历。

![20220905_112507000_iOS](https://user-images.githubusercontent.com/102615346/188439126-fc5365cb-f147-429f-9847-21dcc4ac9c6a.png)
![20220905_112513000_iOS](https://user-images.githubusercontent.com/102615346/188439156-0ba964a4-53df-4f68-a7de-f378a8e3fa43.png)
![20220905_112517000_iOS](https://user-images.githubusercontent.com/102615346/188439178-b5dca53c-8fbf-46a7-a1f3-6ef01b3fdc5f.png)

**Comment by robertying** [comment]
请参考这个 issue：https://github.com/robertying/learnX/issues/1012
看看返回的结果是什么

**Comment by Ageha-Xia** [comment]
![image](https://user-images.githubusercontent.com/102615346/188555997-9fbde24a-9915-4867-bcd4-6ec939058456.png)

**Comment by Ageha-Xia** [comment]
同#1012一样，即使修改了日期到最近一段时间，仍然返回thu_learn_lib_jsonp_extractor([])
![image](https://user-images.githubusercontent.com/102615346/188556851-d6e737a2-29a5-4fd1-9148-5f929ba0ab60.png)

**Comment by robertying** [comment]
`p_end_date` 写的不对。。以及尽量使用最近一个月的日期

**Comment by Ageha-Xia** [comment]
![image](https://user-images.githubusercontent.com/102615346/188558051-72e05f27-4b62-48ef-9bec-25da8c089893.png)
修改到最近一个月也没有显示

**Comment by robertying** [comment]
如果是研究生的话，需要把 `bks` 改为 `yjs`

**Comment by Ageha-Xia** [comment]
但我是本科生

**Comment by robertying** [comment]
这说明网络学堂还没有生成课表，可能需要等几天。
如果前往网络学堂，点击右上角的日历进入 UI，能否看到课程？

**Comment by Ageha-Xia** [comment]
我的夏季学期课程已经结束，因而不能看到课程，那么我再等几天吧

**Comment by robertying** [comment]
这个 API 是和网络学堂的日历 UI 一致的，如果网络学堂日历有课程，但是 app 无法获取课表，可以再 open。
