### ISSUE TITLE
课程信息共享应该包括网课信息

### ISSUE THREAD

**Issue by Triang-jyed-driung** [robertying/learnX#1026]
现如今很多同学紫荆灰码，不能进教室，并且想旁听网课。如果有网课信息将更加方便。

网课信息一般在群公告或“在线课表”中，包含会议号和密码，只需提出来即可。有比较明显的关键词（线上，会议，密码，腾讯会议，Zoom，瞩目等）。训练一个简单的NLP或者直接按关键词提取应该不是什么难事。

少数老师会直接将会议号发到微信群，或许可以开放一个手动补全网课信息的通道。

**Comment by robertying** [comment]
课程信息共享的初衷还是以课程评价为主，上课时间地点为辅。虽然没人写评价……
网课会议链接分享存在风险，疫情初期就出现好几次清华腾讯会议被校外不明人士轰炸导致教学混乱的情况。这部分信息与网络学堂文件/通知类似，应该属于小范围分享的内容，即使用账号系统屏蔽校外人士，很多老师也不会愿意对已选课同学之外的学生开放。
其次，`训练一个简单的NLP或者直接按关键词提取应该不是什么难事`。😅
