### ISSUE TITLE
Add windows bulid!

### ISSUE THREAD

**Issue by MacHacker-xyz** [robertying/learnX#1027]

**Comment by robertying** [comment]
Windows 下的 React Native 还是不够成熟，对很多库支持有限，很多功能比如日历同步会缺失。暂时没有计划支持 Windows，如果需要改善 Windows 下的网络学堂体验，建议可以用 Harry Chen 的 Learn Helper 浏览器插件。

**Comment by zhaozkTHU** [comment]
Learn Helper的地址是什么呢

**Comment by robertying** [comment]
@zhaozkTHU https://github.com/Harry-Chen/Learn-Helper
