### ISSUE TITLE
作业提交失败

### ISSUE THREAD

**Issue by HustreLiny** [robertying/learnX#1028]
Android作业提交pdf文件多次失败，始终复现，中英文名均出现失败现象
![Screenshot_2022-10-09-20-00-23-703_io robertying learnx](https://user-images.githubusercontent.com/42056233/194755713-5b8325d4-2e99-4916-b240-ae1c09e7d771.jpg)

**Comment by robertying** [comment]
作业提交需要 debug 的话，可能需要同学你的支持。我这边没有办法直接判断。

1. 我可以给你提供一个显示错误信息的版本，你再将错误信息反馈给我；
2. 或者你可以临时更改账号密码并经邮箱提供给我，经我测试后再修改账号密码。

**Comment by HustreLiny** [comment]
> 作业提交需要 debug 的话，可能需要同学你的支持。我这边没有办法直接判断。
> 
> 1. 我可以给你提供一个显示错误信息的版本，你再将错误信息反馈给我；
> 2. 或者你可以临时更改账号密码并经邮箱提供给我，经我测试后再修改账号密码。

1即可，请把apk发给我，我看下会不会用

**Comment by robertying** [comment]
[app-arm64-v8a-release.apk.zip](https://github.com/robertying/learnX/files/9816898/app-arm64-v8a-release.apk.zip)

这个版本hu会把作业提交时候的错误显示出来。

**Comment by SiyuanQAQ** [comment]
> [app-arm64-v8a-release.apk.zip](https://github.com/robertying/learnX/files/9816898/app-arm64-v8a-release.apk.zip)
> 
> 这个版本会把作业提交时候的错误显示出来。

![Screenshot_2022-10-22-22-35-33-562_io robertying learnx](https://user-images.githubusercontent.com/43287062/197345088-60cee52d-958c-4c14-80d0-1cdcf7ef1a5a.jpg)

这是用了新版本之后显示的错误信息（其实就是empty）

**Comment by robertying** [comment]
Fixed via 934a7f7f08dff1ef51f85d442b6a9ccf8c10c8ac

@HustreLiny @SiyuanQAQ 请尝试 releases 的最新 13.16.0 版本。如果还有问题，请 reopen。
