### ISSUE TITLE
多端同时开启作业自动同步到提醒事项会重复添加

### ISSUE THREAD

**Issue by lurf21** [robertying/learnX#1029]
环境：IOS 16.0.2，iPadOS 15.4
软件版本： 13.15.0
描述：在手机和平板上同时开启作业自动同步时提醒事项中会重复添加同一个作业，希望在未来能添加去重功能，谢谢！

**Comment by robertying** [comment]
只在一个设备上开启同步就行，或者在日历应用里，应该能选择隐藏某个日历。
不好做去重。
