### ISSUE TITLE
安卓端作业名称支持中文

### ISSUE THREAD

**Issue by HustreLiny** [robertying/learnX#1030]
作业提交失败问题已解决，感谢。
文件名是否有可能不移除中文？希望能用这个app完全替代网络学堂主要功能。

**Comment by robertying** [comment]
React Native 对 Android 上的 HTTP 请求有特别处理。想修复但一直搁置了。今天有机会给他们提了个 PR，如果上游修复的话，这个问题在 learnX 也可以解决了。

**Comment by robertying** [comment]
可以测试下这个版本吗？

[app-arm64-v8a-release.apk.zip](https://github.com/robertying/learnX/files/10145836/app-arm64-v8a-release.apk.zip)

**Comment by HustreLiny** [comment]
并不行，中文名依然被移除


 
---原始邮件---
发件人: "Rui ***@***.***&gt;
发送时间: 2022年12月3日 14:24:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [robertying/learnX] 安卓端作业名称支持中文 (Issue #1030)




 
可以测试下这个版本吗？
 
app-arm64-v8a-release.apk.zip

**Comment by robertying** [comment]
[v2.apk.zip](https://github.com/robertying/learnX/files/10161980/v2.apk.zip)

hmm，可以尝试下这个版本吗？

**Comment by HustreLiny** [comment]
测试了一下，目前没有问题，中文名正常


 
---原始邮件---
发件人: "Rui ***@***.***&gt;
发送时间: 2022年12月6日 11:30:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [robertying/learnX] 安卓端作业名称支持中文 (Issue #1030)




 
v2.apk.zip
 
hmm，可以尝试下这个版本吗？
