### ISSUE TITLE
作业附件和提交附件重名不能区分

### ISSUE THREAD

**Issue by ayf19** [robertying/learnX#1031]
如果同一个作业里出现了作业附件和提交附件重名的现象，则打开两个文件都会是第一次打开的那个文件，使用版本v13.16.0（build 2351），使用平台 macOS 13.1

**Comment by robertying** [comment]
目前文件保存只根据课程名-文件名，所以同名文件会互相覆盖。后续看看好不好优化。

**Comment by robertying** [comment]
Fixed by cb9a1212f676641a53b141b138b8288d7c8eef2d
