### ISSUE TITLE
通知中无法查看图片

### ISSUE THREAD

**Issue by HustreLiny** [robertying/learnX#1033]
查看一些有图片的通知，图片无法加载。多个课程的多个通知均出现该情况，下图是一个例子
![IMG_20230213_112408](https://user-images.githubusercontent.com/42056233/218363406-5ae20c27-3bd1-44a6-a117-1d5139a6e48f.jpg)

**Comment by robertying** [comment]
请问图片的 URL 大致是什么形式的？在网络学堂网页版应该能看到。

**Comment by robertying** [comment]
这些图片点击链接，可以直接预览吗？还是会自动下载

**Comment by HustreLiny** [comment]
1.会直接下载
2.网络学堂上正常，不知道这个是不是HTML tag
![image](https://user-images.githubusercontent.com/42056233/218673200-009a706b-4d14-4eef-b825-f3fd05ab90fd.png)

**Comment by robertying** [comment]
Fixed by 361177245d1eb7b6d6cd3518f5985a3dfba1fda9
