### ISSUE TITLE
通知中图片显示问题并未被修复

### ISSUE THREAD

**Issue by HustreLiny** [robertying/learnX#1034]
https://github.com/robertying/learnX/issues/1033#issue-1581583124
然并卵，14.0.2并没有修复该问题......

**Comment by robertying** [comment]
应该是只对 iOS 生效了，Android 需要手动设置 cookies。

**Comment by robertying** [comment]
Fixed by a97190e9f846fc26776f479b8fb0e5f55bc922b4
