### ISSUE TITLE
同一个作业下相同名称的作业附件和批改附件会产生冲突

### ISSUE THREAD

**Issue by liang2kl** [robertying/learnX#1036]
版本：v14.0.2 (build 2450)

现象：在作业附件和批改附件文件名相同的作业下

1. 打开任意一个上述文件（文件 1）
2. 打开另一个文件（文件 2），此时显示的是文件 1
3. 文件 2 手动刷新，此时显示正常（此时打开文件 1 显示的为文件 2）

<img width="330" alt="截屏2023-02-26 09 17 53" src="https://user-images.githubusercontent.com/50020539/221387163-55544f98-737f-44bf-adb7-4f4fac49bba9.png">

**Comment by liang2kl** [comment]
与 https://github.com/robertying/learnX/issues/1031 类似问题

**Comment by robertying** [comment]
感谢指出，在 ca0410c197ea15e771e3fa7d7baf6ce89956654c 修复。
