### ISSUE TITLE
希望mac端与ios端可以同步设置

### ISSUE THREAD

**Issue by QuentinHsuow** [robertying/learnX#1039]
ios端屏蔽、归档的课程需要在mac中再手动操作一次。另外，mac似乎并不可以屏蔽课程。

**Comment by robertying** [comment]
因为 learnX 并没有自己的账户系统，支持设备同步实现起来会比较不直接；再者没有特别多的设置需要同步，此需求对体验的改善不强烈，暂时不考虑实现。

Mac 下因为是 iPad 版本的变种，需要使用鼠标在卡片上左划来展示额外的选项。
