### ISSUE TITLE
iPad版本无法同步日历

### ISSUE THREAD

**Issue by Futrime** [robertying/learnX#1041]
![E7C88E70-2514-4BA3-A746-349787CB5338](https://user-images.githubusercontent.com/35801754/232712526-1fa5583a-433f-4035-ac07-0df65a4782ae.jpeg)

**Comment by robertying** [comment]
app 版本是多少呢？
是否在校园网下呢？
网页版网络学堂进入后右上角的日历显示是否正常呢？
app 是否有正确的日历权限呢？
重装 app 或者注销后重新登录是否解决问题呢？
