### ISSUE TITLE
对开屏登陆和文件存储的建议

### ISSUE THREAD

**Issue by HustreLiny** [robertying/learnX#1042]
目前应用应该是开屏登陆，但是如果登陆失败便不能进去应用。我使用过程中多次发现即使校园网连接正常，可以访问其他网页，应用却难以登陆，表现为长时间保持在开屏画面无反应，没有对网络连接问题的提示。
我对此的解决办法是使用流量登陆，但是learnX对文件的下载和存储也有问题，文件下载后，应用一旦被杀掉后台就要重新下载，流量消耗严重。
希望开发者可以试着解决存储问题，比如在文件查看页面增加一个保存按钮，方便把需要频繁查看的文件长期保存在本地。网络问题我也搞不太清楚，或许可以进一步排查XD

**Comment by robertying** [comment]
开屏登录问题我有感觉到，但是我在美国这边也不是经常能卡好几秒，所以没修。这几天可以搞一下。
文件下载后应该是会自动缓存的，不应该存在要重新下载的问题，除非是下载到一半被杀。请问是否可以复现？

**Comment by HustreLiny** [comment]
感谢。
文件问题稳定复现，点开文件下载，退出该页面后再次点击文件，100％重复下载一遍，甚至不需要被杀后台

**Comment by robertying** [comment]
是 iOS 还是 Android 呢？版本号多少？

**Comment by HustreLiny** [comment]
安卓12，v14.1.4，

**Comment by robertying** [comment]
我这边没法复现，重新安装 app 是否有用呢？重复下载是指进度条很慢走一遍，还是很快的闪过呢？

**Comment by HustreLiny** [comment]
> 我这边没法复现，重新安装 app 是否有用呢？重复下载是指进度条很慢走一遍，还是很快的闪过呢？

我是通过流量监测确定每次点开都下载的，重装没有解决问题，可能是我手机上某些软件的问题。希望您能解决下校园网正常但是卡开屏的情况，毕竟校园网也不费流量的说:D

**Comment by robertying** [comment]
可以试一下比较大的 PDF 文件，如果点开秒加载，应该就是直接用的缓存，没有重新下载。

**Comment by robertying** [comment]
先 close 了，之后如果能够稳定复现，可以 reopen。

**Comment by robertying** [comment]
复现了！

**Comment by HustreLiny** [comment]
泪目😂

**Comment by robertying** [comment]
应该在 v14.2.0 里优化/修复了，请测试。
