### ISSUE TITLE
未能正确获取通知推送的权限

### ISSUE THREAD

**Issue by Stevenclc** [robertying/learnX#1043]
现在给learnX开启了推送权限也显示未授予推送通知权限
系统版本：Intel macOS Ventura 13.5.2，iOS 16.6.1

![image](https://github.com/robertying/learnX/assets/17608501/594c247b-82c1-48b5-aa3c-c07833184f7d)
![image](https://github.com/robertying/learnX/assets/17608501/c0e322ea-3249-4a48-998e-c314dcc71e11)
![IMG_5610](https://cdn.jsdelivr.net/gh/Stevenclc/Typora_Images/IMG_5610.png)
![IMG_5611](https://cdn.jsdelivr.net/gh/Stevenclc/Typora_Images/IMG_5611.png)

**Comment by erbanku** [comment]
同，昨日更新以后就这样了。
![image](https://github.com/robertying/learnX/assets/79493862/f585a938-556a-4edd-b76d-786d470ddca4)

**Comment by robertying** [comment]
Close via 8570920b90080ae2f9893e669e3c1d2790c0c7c3
