### ISSUE TITLE
安卓课表日历同步失败

### ISSUE THREAD

**Issue by YuruiHong** [robertying/learnX#1044]
现象：点击“Sync Course Schedule”每次均报错`Course Schedule Sync Failed. Make sure you are connected to campus networks and try again. If this issue persists for more than three days, file a feedback`，未实际同步

版本：Lineage OS 13, 日历软件Etar version 13，安装包已经更新到`learnX-arm64-v8a-v14.3.0.apk`

确认过的内容：
- 网络学堂显示夏季秋季课表均正常
- 处于校园网环境
- 通知和日历权限开启，且应用权限只有这两项
- 清理、重装、重新登录无效
- 试图删除日历重新同步时，报错`Failed to delete: Exception in HostObject:get for prop 'requestCalendarPermissionsAsync': expo.modules.kotlin.exception.MissingTypeConverter: Cannot find type converter for 'expo.modules.core.arguments.ReadableArguments'.`，此后重新同步依然无效

**Comment by robertying** [comment]
Lineage 是否还有默认的日历 App？建议尝试下系统日历是否能同步。这个日历操作的库通过系统 API 实现的，可能不会考虑到第三方日历的兼容性。

**Comment by YuruiHong** [comment]
可能是我描述不够清楚，我使用的就是Lineage OS内置日历，包名org.lineageos.etar，是Lineage fork了Etar项目作为系统日历。

**Comment by robertying** [comment]
尝试重装，看看能不能修复？

**Comment by YuruiHong** [comment]
原issue中提到我已经尝试过包括重装在内的操作，均得到相同报错。另刚刚在鸿蒙3.0.0.192测试也是相同问题。

**Comment by robertying** [comment]
感谢测试。我手上只有 Pixel 和原生模拟器，会再做一次测试。如果是普遍问题，会及时修复。

**Comment by robertying** [comment]
请尝试 v14.3.1 版本：https://github.com/robertying/learnX/releases

如果还有问题，请根据这个 issue #1012 来判断是网络学堂返回结果问题还是 App 问题。

**Comment by YuruiHong** [comment]
已解决，感谢。
