### ISSUE TITLE
[Feature Request] 日历同步能否选择自动设置为响铃提醒？

### ISSUE THREAD

**Issue by tongyx361** [robertying/learnX#1045]
如题，目前是默认设置为通知提醒

**Comment by robertying** [comment]
日历同步是同步到系统日历，提醒方式是系统日历决定的。

不是很理解什么叫响铃？通知推送时候如果手机没有静音也是有提示音的。

**Comment by robertying** [comment]
hmm 我不认为通过闹钟来进行日历管理是个普遍的需求。(´･_･`)
