### ISSUE TITLE
增加自定义课程同步时间的选项

### ISSUE THREAD

**Issue by YuruiHong** [robertying/learnX#1047]
目前课程同步的时间范围硬编码为一个月，请问是出于什么限制或考虑？个人认为更自然的默认周期是整个当前学期，希望能够自定义。（如果只使用手机日历确实每月点一次就好了，但我目前所知多端同步贵清课表最好的方式还是使用learnX写日历->Calendar Import-Export导出.ics->CalDAV，希望能不必每月重复此流程）

**Comment by UNIDY2002** [comment]
> 目前课程同步的时间范围硬编码为一个月，请问是出于什么限制或考虑？个人认为更自然的默认周期是整个当前学期，希望能够自定义。

这题我会（

当同学的课程数量比较多，导致一次调用 wlxt 接口返回的数据量过大时，wlxt 会报错。

![图片](https://github.com/robertying/learnX/assets/41641284/f2a0982c-cc0c-4f18-a9cb-27890c93fc5c)

**Comment by YuruiHong** [comment]
那设置个几小时的延时也比没有好吧（
主要是导出到系统日历除了看，还有常见的用途是再导出成ics写到第三方日历，只有一个月而且覆盖更新对日历协议非常不友好

**Comment by YuruiHong** [comment]
感觉比较灵活的方法是允许设定更新课表的起始时间，并把时段长度上限设成一个月（虽然我不是开发者体会不到工作量大小就是了x）

**Comment by UNIDY2002** [comment]
> 个人认为更自然的默认周期是整个当前学期

另一个限制是，据我所知，根据学校现有接口无法得知每个学期的起始日和终止日。THU Info 就屡次在学期交界时期被这件事整得很麻。

至于您的其他回复，我不是 learnX 开发者，我就不做评论了。

**Comment by robertying** [comment]
限定一个月范围就是 @UNIDY2002 说的原因。之前经常莫名获取失败，后来发现就是时间长了不行。

如果有导出日历的需求，可以直接用 thu-learn-lib 或者直接访问网址拿数据写入 CalDAV 就行？

**Comment by robertying** [comment]
当然 learnX 也可以一个月一个月拉数据然后合并给写入。之前也不知道为啥没做这个。

**Comment by robertying** [comment]
Closed via 3534944d13011fad9c14682a84bc33b95dc954f1
