### ISSUE TITLE
[feature request] 通过文件分享快速提交作业

### ISSUE THREAD

**Issue by AsakuraMizu** [robertying/learnX#1048]
支持在其他应用中将文件“分享”到 LearnX 后选定作业上传提交，避免需要先将文件保存至文件系统

**Comment by robertying** [comment]
Closed via f825789af2b98c06e2c4108cd366522b47d677f6 and b1dab5341206ebede40b9606ae7568be3696b605

Android 上有点小问题，但是就先这样了吧。

**Comment by AsakuraMizu** [comment]
貌似不是很工作的样子。。。（iPad）

抓了一下包
![图片](https://github.com/robertying/learnX/assets/17076564/14c1c61e-80fa-40de-a24f-6beee01a995a)

应该是传过来的文件没有文件名后缀导致的

**Comment by robertying** [comment]
我自己测试的时候是能看到“uuid.扩展名”的。让我再看看吧。

**Comment by robertying** [comment]
确实是文件名没有扩展名的问题。Fixed via [02401fb](https://github.com/robertying/learnX/commit/02401fbfd71b2a7244aa403076becac57de7c7e1)
