### ISSUE TITLE
学期切换再切换回来后，本学期课程无法正确显示

### ISSUE THREAD

**Issue by operator22th** [robertying/learnX#1049]
**问题描述**

学期切换再切换回来后，本学期课程均无法正确显示，只会显示空白，而且登出后重新加载仍无法正常使用。

**复现过程**

1.  切换学期到上一学期
2.  切换回本学期

**截图**

**运行环境**

 - App 版本：v14.3.2
 - 设备型号：iphone13 & ipad
 - 系统版本：16.6.1

**补充内容**

**Comment by robertying** [comment]
请问下拉刷新手动加载内容能否解决问题呢？

**Comment by operator22th** [comment]
学长您好，下拉刷新手动加载、卸载后重装以及登出后加载似乎都不能解决问题。
切换在以往学期之间是正常的（比如22-春和22-秋）但就是不能切回到本学期了（从22-春切换到23-秋时，课程列表的fragment title更改为23-24学年秋季，但课程列表没有相应地发生改变）。
如果直接卸载或登出后，会现实正常的学期，但是课程，文件和作业都显示”无内容“，课程数量为0.

**Comment by robertying** [comment]
网络学堂网页版的当前学期页面是否发生了什么变化呢？感觉这个问题上个月还不存在。

**Comment by robertying** [comment]
在“课程” tab 手动下拉刷新有没有效果呢？

**Comment by robertying** [comment]
可否帮忙确认，受影响学期的部分课程没有上课时间和地点的信息？https://github.com/Harry-Chen/Learn-Helper/issues/145

**Comment by operator22th** [comment]
抱歉 前面在上课
网络学堂网页版的当前学期页面没有发生变化。
以前的版本确实没有遇见此问题。
手动刷新后仍然显示过去学期课程（有加载的动态效果，但加载后仍为过去学期内容）
全部学期均显示不出 应该都有时间地点

**Comment by robertying** [comment]
可以尝试下 Learn Helper 这个浏览器插件吗，是否能在那上面加载出来。

因为我们用的是同一个库。

**Comment by operator22th** [comment]
抱歉，我现在手上只有iPad和平板，暂时没有办法测试插件，会在明天给您测试结果。
再次抱歉，我前面的评论有误，点击issue后发现确实有同样的情况，即我也有这个“形势与政策小班课”。

**Comment by robertying** [comment]
发布了一个热修，请尝试触发热更新下载：进入 App，等待一会，然后强制关闭 App，重新进入。确保 App 版本为 v14.3.3 或 v14.3.4，验证该问题是否被修复。谢谢！

**Comment by operator22th** [comment]
问题已经完全修复，万分感谢！
