### ISSUE TITLE
连续三天无法同步课表

### ISSUE THREAD

**Issue by SELFLOVER03** [robertying/learnX#1050]
**问题描述**
连续三天无法同步课表

**复现过程**
1. 同步课表

**截图**
![IMG_7859](https://github.com/robertying/learnX/assets/116138507/bd394b58-2fbe-4270-8e3d-44d71cc46312)

**运行环境**

 - App 版本：最新版
 - 设备型号：iPhone13pro
 - 系统版本：IOS17.0.3

**补充内容**

**Comment by robertying** [comment]
请问 iOS 设置中 App 的日历权限是否开启并且是完全访问权限？

如果作业同步选择同步到日历，日历中是否会出现最近的作业？

**Comment by robertying** [comment]
请尝试 v14.5.0 是否解决问题。如果还有问题请 reopen。
