### ISSUE TITLE
[Feature Request] 独立控制作业同步到日历和提醒事项 & 作业同步内容去重

### ISSUE THREAD

**Issue by adstellaria** [robertying/learnX#1051]
首先感谢作者的辛苦工作！从本科到研究生已经使用了五年时间，体验一直相当良好！不过现在有两个建议希望作者考虑是否合适：

1. 目前作业同步到日历或者提醒事项是一个开关同时控制的，也就是同步到日历或者同步到提醒事项只能选择一个，但我希望两者能否可以实现独立控制，即可以实现同时同步到日历以及提醒事项，并且可以单独设置两者的截止/提醒时间，这样可以实现更加灵活的同步；

2. 在同步作业到日历或提醒事项时，如果多次刷新作业，就会出现重复同步的情况，即同一个作业会出现多项日程或者提醒事项，不知道是否有办法实现去重（我设想的解决方案是先统一删除旧内容再同步新内容，但不知道这样处理是否会有副作用）

再次感谢作者！

**Comment by robertying** [comment]
关于第二点，现在 learnX 就是这么做的。这更可能是个 bug。

尝试清除所有日历和提醒事项来重置，再重新同步，是否解决这个问题？

**Comment by adstellaria** [comment]
> 关于第二点，现在 learnX 就是这么做的。这更可能是个 bug。
> 
> 尝试清除所有日历和提醒事项来重置，再重新同步，是否解决这个问题？

经过一些测试感觉应该可以稳定复现这个bug，具体操作方法为：

在清除所有日历与提醒事项后，先刷新一次作业以同步作业到日历，然后切换到同步作业到提醒事项刷新一次作业，这时再切换到同步作业到日历并刷新作业就会出现重复添加的情况（如果再切换一次到提醒事项，则提醒事项也会重复添加）。

如果一直保持同步作业到日历或者同步作业到提醒事项选项不变则不会出现这个问题。

**Comment by robertying** [comment]
感谢确认，这个应该是 expected 的，因为App 只储存日历或者提醒事项的ID，所以每次切换同步目标时候存的ID 都会被清空。如果允许同时同步那就会单独存 ID 了

**Comment by robertying** [comment]
Closed via df34cde7b954d31385d6521eb511cb9a8a125782
