### ISSUE TITLE
同步的课表不定期被全部删除

### ISSUE THREAD

**Issue by YuruiHong** [robertying/learnX#1052]
**问题描述**

使用课表同步功能同步到系统日历的课程不定期被全部删除，不确定产生时机，也不确定是否由learnX还是日历应用本身导致。日历应用是Lineage OS系统自带的。

**复现过程**

1.在校园网环境使用课表同步功能，成功同步
2.等待若干天
3.所有课表被删除，表现为无法在日历中显示，但在Calendar Import-export应用中仍可看到该日历和相应记录

**已尝试的解决方案**

1.可以重新手动同步，但是上述显示问题随机出现而不知道如何解决

- App 版本（设置 - 关于）：14.5.0
- 设备型号：Redmi K30i 5G
- 系统版本：Lineage OS (Android 13)

**补充内容**

**Comment by robertying** [comment]
请问是日程被删除，还是整个 “learnX 课表”日历被删除呢？

**Comment by YuruiHong** [comment]
抱歉一直忘记回复，正如我之前所说

> 所有课表被删除，表现为无法在日历中显示，但在Calendar Import-export应用中仍可看到该日历和相应记录

日程和日历都没有被删除，导出仍为对应有效的ics，没有证据指向learnX的bug，我现在认为Etar日历出问题的可能性更大

**Comment by robertying** [comment]
可以用其他日历软件验证下，有问题可以 reopen。
