### ISSUE TITLE
macOS下文件预览显示空白

### ISSUE THREAD

**Issue by BaicaiBear** [robertying/learnX#1053]
**问题描述**
macOS下文件预览功能恢复，但是加载过后界面空白.

**设备信息**
MacBook Pro 14英寸，2021年
Apple M1 Pro
老图书馆校园网环境

**已尝试的解决方案**

尝试切换深色/浅色模式无效

**截图**
![截屏2023-11-01 19 32 08大](https://github.com/robertying/learnX/assets/28836266/a44a1ed0-fe01-4237-a205-c68f3734f981)

**Comment by robertying** [comment]
请确认系统版本和 App 版本，这两个最关键呀

**Comment by lemonchu** [comment]
软件版本 v14.5.1
macOS Sonoma (14.0)
MacBook Pro 2021，北馆校园网，也有同样的问题。

**Comment by robertying** [comment]
macOS 14.1 下我测试是可以正常显示的，可能是 14.1 修复了这个 WebView 预览的问题。什么时候升级到 14.1 后可以帮忙再测试一下。@lemonchu

 目前可以通过右上角的“打开”按钮来从 Preview 打开 PDF。cc @BaicaiBear

**Comment by lemonchu** [comment]
我升级到14.1后，learnX也能正常预览文件了，多谢！ @robertying

**Comment by robertying** [comment]
> 我升级到14.1后，learnX也能正常预览文件了，多谢！ @robertying 

感谢测试。

我会更新下只在14.1及以上重新启用预览。

**Comment by robertying** [comment]
Fixed via 445be6e4c3c8a6b836678a12172c3c99af198a5b
