### ISSUE TITLE
在unfinished assignments的界面一刷新就会显示成其他的assignments，且下拉栏非常卡顿

### ISSUE THREAD

**Issue by SELFLOVER03** [robertying/learnX#1054]
**问题描述**

每次刚进入learnX应用时，在unfinished assignments的界面一刷新就会其他的assignments（目前出现过all，favorite，archived），且此时下拉栏非常卡顿；当再回到unfinished assignments的界面后，再次刷新就可以稳定显示unfinished assignments。

**复现过程**

如上。

1.
2.
3.

**已尝试的解决方案**

1. 无，因为这个bug除了会卡一次其他影响不大
2.
3.

**截图**

**运行环境**

- App 版本（设置 - 关于）：14.5.1
- 设备型号：Iphone13pro
- 系统版本：IOS17.0.3

**补充内容**

**Comment by robertying** [comment]
请问切换学期再切换回来，或者退出登录是否解决问题？以及是否有实验室探究这种作业爆炸的课？

**Comment by robertying** [comment]
没有回复先 close 了，有问题反馈可以 reopen。
