### ISSUE TITLE
建议增加指定文件下载位置功能

### ISSUE THREAD

**Issue by suxj22** [robertying/learnX#1055]
软件下载的文件均保存在MacOS的Library目录下，寻找比较困难，而且已经下载的文件经常会被删除。建议增加指定文件保存的位置功能，是否删除文件由用户决定。

**Comment by robertying** [comment]
理论上 macOS 下的下载文件是对用户透明的，通过打开按钮在 Preview 打开，如果需要额外保存可以在 Preview 另存为。Library 的路径不应该被依赖。

设置-文件 中可以选择将文件保存到对应 App 沙箱的文档目录中，就不会被系统缓存机制删除了。

**Comment by robertying** [comment]
learnX 不计划成为网络学堂下载器，我没记错 GitHub 上有脚本可以下载内容并且整理，可能更符合你的需求。

learnX 目前可能还是作为一个预览渠道。
