### ISSUE TITLE
作业同步到日历所占时间长度建议

### ISSUE THREAD

**Issue by study-i-n-g** [robertying/learnX#1056]
更新后，同步的作业所占时常变为30min，在 日历-周 中过于狭窄，导致变成`...`,无法显示有效作业名称。
<img width="563" alt="image" src="https://github.com/robertying/learnX/assets/109450395/c13f5d08-b262-4c29-9b49-a1919546ee06">
高的是更新前同步的的显示出作业名称是“留数定理”，低的是更新后同步的，几乎没有有效信息，已完成作业由于增加了勾，更加显示不出来。建议增宽或用户可选宽度。而且细长条也不美观。

**Comment by robertying** [comment]
日历日程具体如何展示是日历软件自己选择的，learnX 无法控制这些行为设置。

**Comment by robertying** [comment]
大多数日历（Google Calendar）的默认时长都是半小时，所以日历软件基本上都对这个时长有优化。learnX 也更新成半小时也是为了与其保持一致。如果显示不完全，请考虑更改日历视图或者换用其他日历软件。

**Comment by robertying** [comment]
仔细想了一下，理解了你说的宽度的意思。理论上可以支持自定义日程时间长度，但是优先级稍稍靠后。

**Comment by robertying** [comment]
Fixed via f87b83277cf7f2a9fb31b9f15599d0d7fd519753
