### ISSUE TITLE
作业栏闪退

### ISSUE THREAD

**Issue by Sicily-love** [robertying/learnX#1057]
**问题描述**

平板和手机端尝试切换到作业栏目会闪退

**复现过程**

1.打开learnX
2.切换到作业栏

**已尝试的解决方案**

1.后台删除进程重启
2.切换设备
3.尝试切换到其他栏目，无闪退

**运行环境**

- App 版本（设置 - 关于）：v15.5.0
- 设备型号：华为matepad pro10.8,matepro30
- 系统版本：鸿蒙4.0.0.126,4.0.0.116

**Comment by robertying** [comment]
应该是某个作业导致的。请查看可疑的作业，关注作业描述。

可以先去课程 tab 隐藏课程，然后切换到作业 tab 看哪个课程设为不隐藏后开始闪退，来缩小范围。

**Comment by robertying** [comment]
ok 我知道哪里会有问题了……

**Comment by robertying** [comment]
请确认热修版本 v14.5.2 是否解决问题。热修触发方式：进入 App，等待一段时间，强制退出 App （上划），重新进入，热修应该就已经在了。

**Comment by robertying** [comment]
没有回复先 close 了，有问题反馈可以 reopen。
