### ISSUE TITLE
可否增加手动选择语言功能

### ISSUE THREAD

**Issue by alanwangcot** [robertying/learnX#1058]
现在看起来表现是跟随系统语言？苹果系统英文用着舒服，但会导致learnX也自适配到英文，一些课程英文看起来很难受。
在iOS上可以通过系统设置里改app偏好语言实现跟系统不同语言，在macOS上暂时没找到手动更改语言的方法。
感谢!

**Comment by robertying** [comment]
macOS 下也是可以给 App 单独设置语言的：https://support.apple.com/zh-cn/guide/mac-help/mh26684/mac

**Comment by alanwangcot** [comment]
受教了，感谢
