### ISSUE TITLE
iOS：希望增加从其他应用分享作业后，在提交作业前可自定义修改文件名的功能

### ISSUE THREAD

**Issue by lemonchu** [robertying/learnX#1059]
缘由：从Goodnotes以【姓名：学号格式】导出并分享作业到learnX后，在提交时被自动命名为作业标题-提交。这个命名规则会对老师批改作业后统计成绩造成困扰。
故提个小小意见，能在提交作业的时候自定义最终提交的作业名

**Comment by robertying** [comment]
请问 App 版本是多少？自定义作业附件名功能已经存在的，直接编辑附件名输入框即可。
