### ISSUE TITLE
2023-2024 春季学期选项不出现

### ISSUE THREAD

**Issue by Gravifer** [robertying/learnX#1061]
**问题描述**

在界面中，无法切换至当前学期

**复现过程**

直接在相应界面进行验证

**已尝试的解决方案**

重启和更新客户端；切换各客户端平台

**截图**

![wsa-screenshot](https://github.com/robertying/learnX/assets/44160838/78b3d2b4-7265-4af5-989f-219e9a81005c)

**运行环境**

v14.6.2 @ Android, WSA, MacOS

**Comment by robertying** [comment]
学期列表是从网络学堂拉取的，请问在网络学堂网页版中能否看到所有学期（包括最新的）呢？

**Comment by robertying** [comment]
注销登录然后重新登录，是否解决问题呢？

**Comment by robertying** [comment]
看了一下 “最新学期” 应该是能获取的，但是可能目前 “所有学期列表” 中网络学堂没有返回包含 “最新学期” 的结果。

理论上如果你不进入这个学期选择界面，而是注销后重新登录，会默认选中最新学期。

**Comment by Gravifer** [comment]
> 注销登录然后重新登录，是否解决问题呢？

在发出原post时已尝试，但没有解决问题； 今日刷新发现问题已解决，但原因不明．
总之，似乎 issue 可以先关闭了，看起来的确是某些网络学堂方面的问题．

我猜测这和我昨天进行了大幅度的选课调整有关系；网络学堂的内容也到今天才变为和我当前选课状态一致．

**Comment by Gravifer** [comment]
我尝试在昨天再次临时添加了选课，目前网络学堂和 Learn Helper 的课程信息已更新，不过 LearnX 还暂时没有；不知道是不是加上了每日同步一次之类的限制？
(看起来预期不会影响功能，因此不重新打开 issue)

**Comment by robertying** [comment]
在课程 tab 下拉刷新是否有用？

**Comment by Gravifer** [comment]
发生了一些诡异的情况
我发现学期自动跳回了秋季学期，但课程列表停留在本学期本周二(2.27)我的选课状态
在我将学期重新手动换到春季后，新增加的课程出现在列表里了（从而完成了我使它在CourseX中被记录的目标）
我尝试了重新手动切回秋季学期，没能复现问题．
看起来我似乎无法提供更进一步的有用信息，抱歉 

> 在课程 tab 下拉刷新是否有用？
这项操作在今早尝试了的，并没有起作用

看起来至少您先不用太过在意这份偶然报告，姑且作为一个 closed issue 存档吧

**Comment by robertying** [comment]
切换学期时候课程会自动更新的。有可能某次切换学期之后课程更新失败了，那么就会出现学期和课程对不上的情况。

手动再次切换会重新触发课程更新，或者在课程页面下拉刷新也是可以的。
