### ISSUE TITLE
ios课表和作业无法同步至日历

### ISSUE THREAD

**Issue by 1YoungJack** [robertying/learnX#1062]
**问题描述**

**复现过程**

1.
2.
3.

**已尝试的解决方案**

1.
2.
3.

**截图**

**运行环境**

- App 版本（设置 - 关于）：
- 设备型号：
- 系统版本：

**补充内容**

**Comment by robertying** [comment]
同学你好，请完整填写问题模板，以便于我排查问题。

**Comment by robertying** [comment]
没有详细的问题描述，先 close 了。之后有补充可以重新 open。
