### ISSUE TITLE
分组查看

### ISSUE THREAD

**Issue by wangdong2021** [robertying/learnX#1064]
现在的版本似乎无法查看网络学堂中的“我的分组”板块，一些课程的分组信息会显示在这里

**Comment by robertying** [comment]
可否提供下“我的分组”界面的截图？

**Comment by wangdong2021** [comment]
![Uploading 截屏2024-04-12 10.15.56.png…]()

**Comment by wangdong2021** [comment]
![截屏2024-04-12 10 15 56](https://github.com/robertying/learnX/assets/80828087/97f9629a-1975-4648-b9ac-48636ebc98ed)

**Comment by robertying** [comment]
了解了。这么看的话这个功能不能算是高频，基本上一个学期内分组是固定的。learnX 作为网络学堂的补充，而不是代替，并没有覆盖所有网页版的功能，所以暂时没有计划实现这个需求。

除非这个分组会影响到上传作业，或者其他核心功能？

**Comment by robertying** [comment]
没有回复，先暂时 close 了。
