### ISSUE TITLE
日历格式崩坏

### ISSUE THREAD

**Issue by lemonchu** [robertying/learnX#1065]
**问题描述**

最新版本（v14.7.1 build 3111）下，同步课表和作业到日历提醒事项时，日历格式崩坏，没有紫色，而且所有日程是“新建日程”。
同时，macOS环境下，日历小组件会跑满CPU。

**复现过程**

1. 设置-》日历与提醒事项
2. 同步课表
3. 检查iOS日历

**已尝试的解决方案**

1. 更换设备、多次同步

**运行环境**

- App 版本（设置 - 关于）：v14.7.1 build 3111
- 设备型号：MacOS / iPhone 11 都有故障
- 系统版本：Sonoma 14.4.1 / iOS 17.4.1

**Comment by robertying** [comment]
感谢反馈！Fixed via f472e63715926c64533cc024a1aabdfdcdea9945

**Comment by robertying** [comment]
日历小组件的问题感觉和 learnX 不相关，不知道是不是人家对很多同名事件的处理有 bug 导致的。至少现在 learnX 的日历同步正常了。

**Comment by lemonchu** [comment]
MacOS的日历同步也会出类似的问题，现在iOS的已经修好了，macOS也会修好嘛

**Comment by robertying** [comment]
macOS 和 iOS 使用的 API 是一样的
