### ISSUE TITLE
[Bug] 提交作业后不再更新绿色对号✅

### ISSUE THREAD

**Issue by lemonchu** [robertying/learnX#1066]
### 问题描述

如题，在网络学堂提交作业后，learnX刷新后可以显示作业已经提交，但是已经设置的提醒事项却不会被标记为完成，日历里面也是。

### 复现过程

1. 提交一份作业
2. 刷新learnX
3. 检查日历和提醒事项

### 已尝试的解决方案

1. 多次刷新
2. 重新打开日历、提醒事项设置权限

### App 版本

v14.7.3

### 设备型号

iPhone 11 和 Macbook 2017

### 系统版本

macOS Sonoma & iOS 17.4.1

**Comment by robertying** [comment]
Closed via 7ff78e693f759a50e905f20fdd8eea1b89e22f6d
