### ISSUE TITLE
[Bug] 移动端登录learnX会自动修改网页版（网络学堂）设置

### ISSUE THREAD

**Issue by zzzzty29** [robertying/learnX#1067]
### 问题描述

在平板上登录learnX之后，网络学堂网页版的语言设置会自动变成中文。

### 复现过程

1.将网络学堂网页版语言设置为英文。
2.重新登录网络学堂网页版，语言设置仍为英文。
3.移动端登录learnX，登录后不进行任何操作。
4.再次登录网络学堂网页版，语言变为中文。
...

### 已尝试的解决方案

每次登录网络学堂时重新设置。

### App 版本

14.7.7

### 设备型号

iPad Pro 4

### 系统版本

iOS17.6.1

**Comment by robertying** [comment]
请问 learnX 语言设置是中文还是英文呢？

**Comment by zzzzty29** [comment]
您好。是中文的，抱歉我没找到在哪调语言（此处有一个捂脸的表情）

**Comment by zzzzty29** [comment]
您好。我尝试调整了一下系统的语言为英文，此时learnX的语言环境变成了英文，但是课程名称依然显示为中文。

**Comment by robertying** [comment]
learnX 会根据 app 语言来更改网络学堂语言，从而保证拉取的课程信息是对应的语言。

更改语言之后，需要在课程 tab 下拉刷新，或者切换学期再切换回来来触发刷新，会获取当前语言的内容。

iOS 支持对单个 app 设置语言，进入系统设置-learnX 来单独设置 learnX 的语言，不需要更改系统级的语言。

**Comment by zzzzty29** [comment]
问题已解决！感谢。
