### ISSUE TITLE
[Feature Request] 自动取消已完成作业的提醒

### ISSUE THREAD

**Issue by hezicyan** [robertying/learnX#1069]
### 功能描述

如题，在将作业同步到日历时，如果有开启日历提醒，希望判断如果作业已经完成就不要提醒。感谢！

**Comment by robertying** [comment]
huh 之前竟然没考虑到这个情况，感谢反馈，会尽快修复。

**Comment by robertying** [comment]
Closed via 89a081dbee4d860db3bf0ab8ccbdab1d0da86e99
