### ISSUE TITLE
[Bug] v14.8.0 更新后，无法再通过其他app分享文件打了learnX提交

### ISSUE THREAD

**Issue by lemonchu** [robertying/learnX#1070]
### 问题描述

在其他App分享文件到learnX，learnX直接闪退，在提交作业的栏目里也不会出现已经分享文件的标识。

### 复现过程

1. 打开Goodnotes（或其他app）
2. 导出一个笔记，分享到learnX
3. 发现闪退

### 已尝试的解决方案

1. 用别的app（比如微信）分享
2. 检查更新

### App 版本

v14.8.0

### 设备型号

iPad Pro 4

### 系统版本

iOS 18.0

**Comment by robertying** [comment]
Fixed via 16e21c168faef77fd0cba62bbbbbd8a2e6e09e93
