### ISSUE TITLE
[Bug] 在iPad上提交作业时上传文件提示框显示不全

### ISSUE THREAD

**Issue by yangqianrui** [robertying/learnX#1071]
### 问题描述

在ipad上提交作业时上传文件提示框显示不全

### 复现过程

在ipad上提交文件

### 已尝试的解决方案

旋转屏幕方向

### 截图

![IMG_0306](https://github.com/user-attachments/assets/501da48e-c15b-41d5-b6f6-2382c78f387c)

### App 版本

v14.9.1

### 设备型号

ipad air5

### 系统版本

iPadOS

**Comment by robertying** [comment]
Fixed via 94e286fd9895c3f1ff52428c3fa4aeaa61336c67
