### ISSUE TITLE
课程屏蔽

### ISSUE THREAD

**Issue by robertying** [robertying/learnX#11]
按各分类屏蔽通知、文件、作业或整个课程

**Comment by Hunter-CH3** [comment]
想请问一下屏蔽的操作是什么？在应用程序中找不到。是否该功能已被移除？

**Comment by robertying** [comment]
前段时间因为功能入口不清楚移除了。最近计划把它和“收藏”等功能以另一种方式展示出来。

**Comment by robertying** [comment]
Closed by 37648759d6f7a0565ec8902872aacffbdc0749da
