### ISSUE TITLE
软件无法打开，无响应状态

### ISSUE THREAD

**Issue by Konano** [robertying/learnX#357]
安卓版本：Android 9
系统版本：Magic 2.1.0
手机型号：Honor 20 Pro

**Comment by robertying** [comment]
App 是哪个版本呢

**Comment by Konano** [comment]
应该是 4.2.0 版本的时候就不可用了

**Comment by robertying** [comment]
是 Google Play 的版本吗？

**Comment by Konano** [comment]
对的

**Comment by robertying** [comment]
抱歉，这是一个已知问题……今天重新 build 了一下，已经 upload 了。

换成 https://github.com/robertying/learnX/releases 里面的呢？

**Comment by Konano** [comment]
换成 releases 里面的 apk 后就可以使用了

**Comment by robertying** [comment]
和 release 里面一样的版本已经上传了，可能明天就能 rollout，到时候再麻烦帮忙测试一下 Google Play 的版本？

感谢！

**Comment by robertying** [comment]
4.2.1 还是有问题，估计是 Google play 打包问题……

**Comment by robertying** [comment]
上传了不使用 aab 的 4.2.2，问题暂时解决。
