### ISSUE TITLE
Google play版仍然无法打开

### ISSUE THREAD

**Issue by EnjoyColin** [robertying/learnX#449]
Google play版无法打开，v5.1.1，换成GitHub上的就可以。环境：Android 9， oneplus7。

**Comment by robertying** [comment]
你是否还在 beta 中？beta 的版本是有问题的，我测试了一下正式通道的 5.1.1 是没问题的。

**Comment by EnjoyColin** [comment]
是在beta中。退出后就好了。谢谢！
