### ISSUE TITLE
[Bug Report]IOS/ipadOS暗夜模式下会出现闪屏

### ISSUE THREAD

**Issue by Hunter-CH3** [robertying/learnX#480]
暗夜模式下点击任意通知/作业/文件均会出现闪屏情况，屏幕会有一瞬间的白色。

**Comment by robertying** [comment]
感谢反馈！这是上游组件的问题。如果我有时间，可能仔细看一下问题然后提 pr 修复。但是现在暂时没有解决办法。

**Comment by robertying** [comment]
Closed by 834a9bde5534527bd49807439a3fc4924f996b24
