### ISSUE TITLE
[Feature Request]IOS端能否添加导入到“提醒事项”的功能

### ISSUE THREAD

**Issue by Hunter-CH3** [robertying/learnX#493]
对于一些时间为23:59分截止的作业，在calendar中的体验不是很好，并且也会污染calendar的timeline。从逻辑上作业的提醒应该是放到reminders里面比较合理？

**Comment by robertying** [comment]
具体的体验不好指的是什么呢？（因为所有作业都是23:59截止的）

从实际的功能上来说，放在日历里面更加方便一些（可以为 app 单独开一个日历）。同时可以利用 Up Next 这个 Widget 直接看到两天内的 event。

**Comment by Hunter-CH3** [comment]
因为23:59的话会显示在一天的最底下，并且因为如果是一个event的话时常又只有一分钟，会被calendar最底下一栏挡住，需要上划才能看到。而且我觉得如果我做完了这个作业就会想要把它关掉，如果是event的话那就只能删掉这个事件（感觉还是reminders里的勾掉会比较方便）。我不太确定reminders是否也提供了calendar那样的接口，之后我如果有时间的话看看能不能自己捣鼓一下发一个PR吧/捂脸

**Comment by robertying** [comment]
我到时候可以再看看，提供一个选择，日历还是提醒事项。但当初我为什么最终没选提醒事项应该是有某个原因的，但是时间过长有点忘掉了。

**Comment by robertying** [comment]
React Native 似乎没有合适的 Reminders 的轮子，这个 feature 可能要暂时放一放了。
