### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by ouzhou** [robertying/learnX#554]
我是一名小前端，刚刚接触rn，正在学习大佬的代码中，遇到几个问题
## 问题
- redux里面写了太多的样板代码，每个请求都有3种状态，如果说一个按钮要加上loading的状态，那每一个请求将会有4种对应的types
- 请求里面是走的 const success = await someRequest()，这样会导致一个问题，当一个页面在加载数据，但是还未加载完成，如果切换到下一个页面，讲道理上一个页面的请求应该被cancel，如果只是判断success，那cancel将不会被处理，代码将会走向catch error分支，如果你正好在捕获异常下面写了toast一类的提示，cancel就也会弹出提示
- 使用babel-plugin-module-resolver处理一下文件路径，减少../../../pathname这样的代码
- 据说在dom上直接使用style会有性能问题，是否考虑一下styled-components这个库

**Comment by ouzhou** [comment]
请教一下，那个启动屏幕是单独在ios安卓设置的吗

**Comment by robertying** [comment]
1. redux 的样本代码好像一直是这样，即使使用 JS 也要写很多样本代码。有一些库能够减少这些代码，但是会使得可读性稍微差一些，而且上手也不是很简单；其次，这里要用 TypeScript，所以需要有一个 well typed 的库，因此选择了这个 typesafe-actions，他的 async action 大概就是这三个状态。而且，我个人认为这三个状态还是很直观的。更重要的原因是，数据的爬取用的是另外一个同学的库，所以我对数据获取没有掌握，只能对包装的函数进行处理。

2. 在 RN 里面，即使更换页面，JS 也会继续运行的吧（还未验证，但是我记忆中如此，因为在用 react-native-navigation 的时候就是把相关逻辑全部放在 NoticesScreen 的，即使页面如何变化，NoticesScreen 的代码都会执行）。其次，和 1 一样的原因，我对数据获取没有控制，因此就写的简单了。如果只是了解结构的话，没有必要在意这里。

3. 这个还是看个人喜好吧，大部分时间用 VSCode 自动 import 的，所以不是很关注。

4. 这个问题我也是知道的，但是真的在应用运行中，内联 style 对性能有多大的影响，比较难说。从个人开发的角度来说，我的目的是更快的出活，也会更注重可读性一点，所以就没有用 StyleSheet 这类 RN 自带方案了。毕竟本应用的样式也没有什么规律，而且我经常在开发时候改样式，这么写算是偷懒吧……

5. 应用启动那一瞬间的启动屏幕必须是在原生端设置的，iOS 的话在 Xcode 里面看比较清楚，Android 直接看几个资源文件就行了。不过由于我用的 navigation 库是 react-native-navigation，所以还是有很多大坑。
