### ISSUE TITLE
无法同步课程到日历

### ISSUE THREAD

**Issue by xalanq** [robertying/learnX#619]
app 版本 v7.0.0

已经找到问题所在，是由于 thu-learn-lib 获取日历爬取的链接得校内访问，校外访问会 404

<https://github.com/Harry-Chen/thu-learn-lib/blob/15c825f86e561ef9bcfd5257b1d95266d577f0cd/src/urls.ts#L180>

但 app 里无相应的提醒。建议增加一个反馈，告诉用户需要接入校园网。

**Comment by xalanq** [comment]
好像接入了校园网也会有问题，似乎是官方把这个接口关了。。

<https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20200201&p_end_date=20200701&jsoncallback=no_such_method>

我取 thu-learn-lib 也提一个 issue 把

**Comment by robertying** [comment]
你得先登录，拿到 cookie 且认证通过了，才能访问这个网址。
最简单的检测办法是，先进入网络学堂，能正常看到日历，然后再直接访问以上网址。或者将完整的 thu-learn-lib 从登录到访问跑一边。
之前的测试是校外也可以访问的，我再看看。

**Comment by xalanq** [comment]
哦哦，原来是这样。我试了下校园网的确不行。

看了一下 thu-learn-lib 的代码和上面的接口，发现不是 app 的问题，应该是 thu-learn-lib 的问题。

见 <https://github.com/Harry-Chen/thu-learn-lib/issues/17>

**Comment by robertying** [comment]
https://github.com/robertying/learnX/blob/acf86823018d5e37a60bf1fb29bdf087d5f6c058/src/helpers/calendar.ts#L153

当时考虑到了这个问题，难道学校又改限制了吗？😅

**Comment by xalanq** [comment]
应该是的哈哈，只能改一下代码了（

**Comment by robertying** [comment]
@xalanq 可否麻烦试一下以下两段时间呢？
0201-0501、0502-0701

**Comment by robertying** [comment]
5642c04d9a28562bbcd836656be3494e87907080 修复了一个月份导致拿不到这学期日历的问题。
其他时间因为那个 api 原本也不稳定，多试几次基本上都能成功。

**Comment by xalanq** [comment]
> @xalanq 可否麻烦试一下以下两段时间呢？
> 0201-0501、0502-0701

我好像没试成功，应该还是那个29天的问题，你看看能不能拆分一下一个学期为多个 29 天。我是 Android 8

**Comment by xalanq** [comment]
harry那边不打算拆了haha他就更新了个注释，所以还是得你来写一下

**Comment by robertying** [comment]
不是 29 天的问题。我测试的大部分人这两个时间段是 OK 的，只是学校的 api 一会能成功，一会会失败。

**Comment by xalanq** [comment]
啊，成功同步了！感谢！
我是miui 11, android 9

**Comment by panda2134** [comment]
iPhone 8P, iOS13.3.1, 在非校园网环境无法获取日历，但是可以更新课程文件等。
使用XCode进行调试，发现控制台里面出现的是SSL Handshake失败

附控制台截图
<img width="989" alt="截屏2020-02-23上午10 55 51" src="https://user-images.githubusercontent.com/7239200/75102782-e4c63980-562b-11ea-8090-93873c62f749.png">

**Comment by panda2134** [comment]
希望可以reopen issue，如果作者需要可以进行进一步复现调试

**Comment by robertying** [comment]
可以新开一个 issue
