### ISSUE TITLE
安卓版课没法同步到日历

### ISSUE THREAD

**Issue by kebamt** [robertying/learnX#620]
我刚升级到7.1.0版本，试了10多次还是没法同步到日历。修复一下，谢谢！

**Comment by robertying** [comment]
1. 请提供型号和 Android 版本
2. 显示同步成功而日历中不存在，抑或是其他情况？

**Comment by kebamt** [comment]
> 1. 请提供型号和 Android 版本
> 2. 显示同步成功而日历中不存在，抑或是其他情况？
vivo X21A Android 9
应该不是抑制，所有权限都开了。
更新后iOS版正常了，能同步。

**Comment by robertying** [comment]
iOS 正常，而 Android 版本显示同步成功而日历中不存在，说明该系统的日历实现和原生 Android 有出入。

之前测试过 iOS、Android AOSP 原生及 MIUI 都是支持同步到日历的，其他系统由于我本人没有机器，无法做进一步测试。

**Comment by kebamt** [comment]
能不能提供一下安卓原生日历下载地址，网上搜不到，谢谢！
还有现在线上上课，同学们对这个软件的需求很大，恳请您尽快修复一下问题，谢谢！

**Comment by robertying** [comment]
今天看一下是否是全 Android 平台的问题。

**Comment by robertying** [comment]
OK，和两个问题有关：
1. 上游 thu-learn-lib 的 `eval` 在 Android Hermes 引擎中有问题：https://github.com/Harry-Chen/thu-learn-lib/commit/09d4f0ec669d57c606e32a124cdbd7ed86acb405
2. 奇怪的是获取日历的 API 有 clear text 内容，被 Android 高版本特效默认屏蔽：d914f80f6522369d6ef2ae536ca1b3fc88dc93a4

新版本 v7.2.0 经测试支持：
- 华为 Android 10
- 小米 Android 9
