### ISSUE TITLE
听说诚招维护者

### ISSUE THREAD

**Issue by mayeths** [robertying/learnX#628]
学长好，似乎您以一种不好的方式从信息办那里出名了，我之前就知道你这个 repo，但没想到信息办还是这么令人不爽，把学生（用户）放到对立面，真有他们的。如果他们能做出令同学满意的东西，我们哪用费力做这些事情。

我想知道这个仓库大概多大？我没用过 rn，但上手应该简单。android 和 ios 是分开代码的吗？如果顺利的话，我半年后也许有时间可以来维护这个 repo 😀

<del>（如果你们都毕业了，那我来做反抗军好了）</del>

**Comment by robertying** [comment]
谢谢你的支持！

React Native 大部分代码集中在 JavaScript （TypeScript）部分，在 `src` 文件夹里面，原生代码主要负责一些初始化操作。

RN 的上手坑还是比较多的，建议有 React 基础再来搞 RN 会比较合适。

**Comment by mayeths** [comment]
我基础应该没问题，现在正在做 [LearniT](https://github.com/mayeths/learnit/tree/ui) 项目，希望能和你进行合作，打通各端 😀

BTW，我是在信息办的 SRT 下开始这个项目的，但就没从他们那里得到什么帮助，还得到了一堆限制（没错，账户和密码是我和那边吵得最厉害的部分。这之后我和他们就没再联系了，那还是2019年6月份的事情）。也许我会为了 SRT 而先忍气吞声，但如果 SRT 注定没好果子吃了，我现在也反手套一个和你们一样 License 好了。信息办还这么恶心人的话，这也是迟早的事。

菜还有理、还有权是大罪。

**Comment by robertying** [comment]
到时候还感兴趣，可以再联系。
