### ISSUE TITLE
情况不妙

### ISSUE THREAD

**Issue by yangwang2001** [robertying/learnX#629]
https://mp.weixin.qq.com/s/zkL2ThpjkdGqzSHen5g1oA

**Comment by mayeths** [comment]
作者已经看到了 https://mp.weixin.qq.com/s/9Ilh2FenfkNYXZouZeZNrQ

**Comment by yangwang2001** [comment]
真是令人不爽。不过诚然，这样的小项目不容易活下去，希望能倒逼信息办做出更好的吧。。

**Comment by mayeths** [comment]
我和他们打过交道，就他们那个样，启动起来也得很久。响应需求这一块，他们绝对没有开源项目厉害。

让他们做出更好的？2001、2015、2018，照这么说 2021 网络学堂，以年计的响应，我们可以对他们产生什么期望？过于滑稽
