### ISSUE TITLE
iOS 13支持

### ISSUE THREAD

**Issue by Berrysoft** [robertying/learnX#630]
打开就闪退。版本：iOS 13.3.1(iPhone 7)

**Comment by robertying** [comment]
iOS 13.3.1 (iPhone 7 Plus)
目前没有发现问题，重装也没有闪退现象。
能否提供更详细的信息，如权限情况等。

**Comment by Berrysoft** [comment]
Emmmmmm听你这么一说我就重装了一下，好了。
大概是升级系统的时候什么地方挂掉了。
