### ISSUE TITLE
iOS 无法同步课程到日历

### ISSUE THREAD

**Issue by robertying** [robertying/learnX#632]
#619

**Comment by panda2134** [comment]
把原内容粘过来

-------------

iPhone 8P, iOS13.3.1, 在非校园网环境无法获取日历，但是可以更新课程文件等。
使用XCode进行调试，发现控制台里面出现的是SSL Handshake失败
用该设备可以手动打开网络学堂并且看到右边的日历区域

附控制台截图
<img width="989" alt="截屏2020-02-23上午10 55 51" src="https://user-images.githubusercontent.com/7239200/75102782-e4c63980-562b-11ea-8090-93873c62f749.png">

**Comment by robertying** [comment]
多尝试几次呢？

**Comment by panda2134** [comment]
也不行
稍后提供一份详细的log

**Comment by panda2134** [comment]
clone了一份，试图使用`yarn run ios:test:debug`调试，但是提示没有 `GoogleService-Info.plist`,似乎是项目使用了firebase导致

不知如何解决？

**Comment by robertying** [comment]
1. 在 Xcode 中移除 GoogleService-Info.plist 的引用
2. 删除 Build Phases 中的
![image](https://user-images.githubusercontent.com/22592111/75129606-a3ee2380-5704-11ea-97fc-6aa80ef5c22f.png)
右上角叉叉
3. 移除 Firebase 的初始化代码
![image](https://user-images.githubusercontent.com/22592111/75129654-dd269380-5704-11ea-908c-0b856bae3524.png)

建议 checkout 到 c398d7c3b3111eadbb2a0ddf3b30e1d416dd954e（7.2.0），且把之前的所有 build 文件夹删除。

**Comment by panda2134** [comment]
使用charles进行抓包，大致结果如下：
### 校园网环境
- POST `https://learn.tsinghua.edu.cn/b/wlxt/common/auth/gnt`: 正常返回ticket，以半角引号包裹
- GET  `https://zhjw.cic.tsinghua.edu.cn/j_acegi_login.do?url=/&ticket=口令内容`
返回了以下内容：
```http
HTTP/1.1 302 Found
Date: Mon, 24 Feb 2020 09:39:01 GMT
Server: Apache
P3P: CP=CAO DSP COR CUR ADM DEV TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE GOV
Access-Control-Allow-Origin: *
Location: http://zhjw.cic.tsinghua.edu.cn/?url=/
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 96
Keep-Alive: timeout=10, max=500
Connection: keep-alive

The URL has moved <a href="http://zhjw.cic.tsinghua.edu.cn/?url=/">here</a>

```
- GET `https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20200201&p_end_date=20200501&jsoncallback=thu_learn_lib_jsonp_extractor`
响应为200，内容中含有大量莫名其妙的空行，以及含有错误信息的页面.
空行可从 [hexdump](https://gist.github.com/panda2134/c1e05217bcfb13b0c35ef25866c9e00f) 中看出，含有大量的 0d 09 0a 20之类
错误信息采用GBK编码，如下：
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
<title>提示信息</title>
<link type="text/css" href="styles/zhjw/css.css" rel="stylesheet">
<link type="text/css" href="styles/zhjw/default.css" rel="stylesheet">
<link type="text/css" href="styles/zhjw/common.css" rel="stylesheet">
<link type="text/css" href="styles/zhjw/topmenu.css" rel="stylesheet">
</head>
<body bgcolor="#eeeeee" style="margin-top:20%;margin-left:20%">
<!-- error -->

 <table border=0 cellpadding=1 cellspacing=1 width='100%' >
  <TBODY>
  <TR>
    <td>
    <font color="#595959" size="5px" >
    
    	response cannot be reset() after committed
	
    </font>

    </td>
  </tr>

</table>

</body>
```

- GET `http://zhjw.cic.tsinghua.edu.cn/?url=/` 返回200，页面内容为“用户登录超时或访问内容不存在”


### 非校园网
最后一步返回 403 forbidden，其余与前述相同

**Comment by robertying** [comment]
在浏览器中操作

1. 登录网络学堂，进入日历，能够看到日历事件。
2. 访问 https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20200201&p_end_date=20200501&jsoncallback=thu_learn_lib_jsonp_extractor

**Comment by panda2134** [comment]
浏览器里面看不了，应该是强制https的原因。

显示阻止了混合内容

**Comment by robertying** [comment]
只要登录过，有 cookie，就可以访问 https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20200201&p_end_date=20200501&jsoncallback=thu_learn_lib_jsonp_extractor

**Comment by panda2134** [comment]
<img width="1215" alt="图片" src="https://user-images.githubusercontent.com/7239200/75145947-f5160b80-5734-11ea-8493-3544322904e8.png">

**Comment by panda2134** [comment]
<img width="797" alt="截屏2020-02-24下午6 43 12" src="https://user-images.githubusercontent.com/7239200/75146222-94d39980-5735-11ea-8465-89af7c41543b.png">

**Comment by panda2134** [comment]
但是在https://zhjw.cic.tsinghua.edu.cn/jxmh.do可以查看，这个页面的表格似乎post的是不同的api

**Comment by panda2134** [comment]
很怀疑是学校教务系统的bug，如果是的话估计得要上游thu-learn-lib进行修改

**Comment by robertying** [comment]
anyway 应该是上游的问题。:/

**Comment by robertying** [comment]
这边测试的好像都没有问题，可能多试几次会有效。
如果再有其他人报 bug，再 reopen 吧～

**Comment by panda2134** [comment]
应该是对 `thu-learn-lib` 的调用的问题。

https://github.com/Harry-Chen/thu-learn-lib/blob/3ccc96d2b9f6162368bef7ce1cd40af201bd5edf/src/index.ts#L117

这里写明了调用查看日历api时不能超过 29 天，但是根据learnX的代码把一学期拆分成两份，超过了29天限制。

正好今天网络学堂混合内容修了，试着用浏览器尝试查询，使用jxmh_out.do查询近29天的课程没有问题。所以说应该只需要改下获取课表的逻辑？

**Comment by robertying** [comment]
之前测试过了，这个29天的限制只在某些时候出现，现在的代码获取不会有这个问题。
