### ISSUE TITLE
希望能添加研究生课程表导入日历功能

### ISSUE THREAD

**Issue by AmateurZhang** [robertying/learnX#637]
研究生的课程表只需要将 `m=bks_jxrl_all` 改为 `m=yjs_jxrl_all `即可

> https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=yjs_jxrl_all&p_start_date=20200201&p_end_date=20200501&jsoncallback=thu_learn_lib_jsonp_extractor

response 示例

> thu_learn_lib_jsonp_extractor([{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-02-17","nr":"现代能量管理系统","sfSjtz":"是","skjc":"3","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-02-24","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-02-24","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-02-24","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"明理楼214","fl":"上课","grrlID":0,"jssj":"12:15","kssj":"09:50","nq":"2020-02-25","nr":"自然辩证法概论","sfSjtz":"","skjc":"2","sm":""},{"dd":"六教6A101","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-02-27","nr":"电气工程仿真技术","sfSjtz":"","skjc":"4","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-03-02","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-02","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-03-02","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"明理楼214","fl":"上课","grrlID":0,"jssj":"12:15","kssj":"09:50","nq":"2020-03-03","nr":"自然辩证法概论","sfSjtz":"","skjc":"2","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-03-09","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-09","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-03-09","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"明理楼214","fl":"上课","grrlID":0,"jssj":"12:15","kssj":"09:50","nq":"2020-03-10","nr":"自然辩证法概论","sfSjtz":"","skjc":"2","sm":""},{"dd":"六教6A101","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-12","nr":"电气工程仿真技术","sfSjtz":"","skjc":"4","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-03-16","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-16","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-03-16","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"明理楼214","fl":"上课","grrlID":0,"jssj":"12:15","kssj":"09:50","nq":"2020-03-17","nr":"自然辩证法概论","sfSjtz":"","skjc":"2","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-03-23","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-23","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-03-23","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"明理楼214","fl":"上课","grrlID":0,"jssj":"12:15","kssj":"09:50","nq":"2020-03-24","nr":"自然辩证法概论","sfSjtz":"","skjc":"2","sm":""},{"dd":"六教6A101","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-26","nr":"电气工程仿真技术","sfSjtz":"","skjc":"4","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-03-30","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-03-30","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-03-30","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"明理楼214","fl":"上课","grrlID":0,"jssj":"12:15","kssj":"09:50","nq":"2020-03-31","nr":"自然辩证法概论","sfSjtz":"","skjc":"2","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-04-06","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-04-06","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-04-06","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"六教6A101","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-04-09","nr":"电气工程仿真技术","sfSjtz":"","skjc":"4","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-04-13","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-04-13","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-04-13","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-04-20","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-04-20","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"4","sm":""},{"dd":"文北楼(文科楼)207","fl":"上课","grrlID":0,"jssj":"17:50","kssj":"17:05","nq":"2020-04-20","nr":"中国马克思主义与当代","sfSjtz":"","skjc":"5","sm":""},{"dd":"六教6A101","fl":"上课","grrlID":0,"jssj":"16:55","kssj":"15:20","nq":"2020-04-23","nr":"电气工程仿真技术","sfSjtz":"","skjc":"4","sm":""},{"dd":"四教4205","fl":"上课","grrlID":0,"jssj":"15:05","kssj":"13:30","nq":"2020-04-27","nr":"现代能量管理系统","sfSjtz":"","skjc":"3","sm":""}])

**Comment by robertying** [comment]
Closed by 88e913b5bbd2424b02a156404f52c706f6a62533
