### ISSUE TITLE
开启通知时收到的邮件无法验证电子邮箱地址

### ISSUE THREAD

**Issue by kebamt** [robertying/learnX#725]
开启通知时收到的邮件无法验证电子邮箱地址，确定是最新的邮件，但是跳转到网页提示过期，无法验证。

**Comment by robertying** [comment]
请问是哪个邮箱呢

**Comment by kebamt** [comment]
网易邮箱（126，163邮箱都不行)
![0144C0D6-5051-4D45-A028-0C835BE29071](https://user-images.githubusercontent.com/59253743/81272291-df4f8b80-907f-11ea-9380-780382f73648.jpeg)

**Comment by kebamt** [comment]
> 请问是哪个邮箱呢

麻烦看一下，谢谢

**Comment by robertying** [comment]
如果只是收到了注册时的第一封邮件，

可以通过以下步骤重新获取验证邮件：

1. 进入推送的登录界面。
2. 使用之前注册账号登录。
3. 下方弹出提示，账号未验证，右侧会有一个“重新发送验证邮件”的按钮，点击来重新获取验证邮件。
4. 请在发送后15分钟内完成验证，否则失效。

**Comment by kebamt** [comment]
按你说的做了，可还是不行。收到邮件后马上打开的链接，试了好几次都不行，新注册账号试了一下也不行。

**Comment by kebamt** [comment]
> 如果只是收到了注册时的第一封邮件，
> 
> 可以通过以下步骤重新获取验证邮件：
> 
> 1. 进入推送的登录界面。
> 2. 使用之前注册账号登录。
> 3. 下方弹出提示，账号未验证，右侧会有一个“重新发送验证邮件”的按钮，点击来重新获取验证邮件。
> 4. 请在发送后15分钟内完成验证，否则失效。



按你说的做了，可还是不行。收到邮件后马上打开的链接，试了好几次都不行，新注册账号试了一下也不行。

**Comment by robertying** [comment]
我重新用 QQ 邮箱注册了，是可以立刻收到邮件并且认证成功的。

可以尝试以下办法：
1. 换用其他邮箱
2. 用 4G 进入验证链接，不使用 Wi-Fi

**Comment by kebamt** [comment]
> 我重新用 QQ 邮箱注册了，是可以立刻收到邮件并且认证成功的。
> 
> 可以尝试以下办法：
> 
> 1. 换用其他邮箱
> 2. 用 4G 进入验证链接，不使用 Wi-Fi

我都试了一下还是不行。
1.用手机4G打开了邮件链接，试着换了邮箱，都不行
2.IPad air 3 上通过手机开的热点打开也不行（WLAN版）

**Comment by robertying** [comment]
换 QQ 邮箱注册呢

**Comment by kebamt** [comment]
> 换 QQ 邮箱注册呢

换了QQ邮箱，还是不行。。。

**Comment by robertying** [comment]
请通过邮箱与我联系。
