### ISSUE TITLE
Mac版公告显示不正常

### ISSUE THREAD

**Issue by fangmaoer** [robertying/learnX#750]
Mac版在日间模式下，公告文字是黑色的，背景是灰色的，难以看清文字。
![截屏2020-05-24 下午1 23 12](https://user-images.githubusercontent.com/50146180/82746397-c5bd7c00-9dc1-11ea-8023-b623f045780b.png)

**Comment by robertying** [comment]
Fixed via ea4a2fe670200f9b855023bf5440aa4c9f346a34
