### ISSUE TITLE
尝试重新验证您的电子邮件地址

### ISSUE THREAD

**Issue by kebamt** [robertying/learnX#751]
反复试了还是开启不了推，按您推荐的方法试了都不行，几乎试遍了所有方法。
提示 ：**尝试重新验证您的电子邮件地址
您的电子邮件地址验证请求已过期，或者相关链接已被使用**

**前面版本没有邮箱认证环节的时候可以开启推送功能，有了认证环节后不行了。。。**
有必要作者可以加我微信：kebamt，我会提供相信信息。
希望LearnX越来越好，谢谢！

![9EC656E8-6835-482C-877D-7666384B4233](https://user-images.githubusercontent.com/59253743/82850076-6b412e80-9f2d-11ea-9625-06ae694aa8b6.png)
![B0B55F08-4722-442A-A323-C67E8DDF652A](https://user-images.githubusercontent.com/59253743/82850079-709e7900-9f2d-11ea-80e9-c0e28d6bad06.png)

**Comment by robertying** [comment]
换电脑上的浏览器呢

**Comment by kebamt** [comment]
> 换电脑上的浏览器呢

使用PC版Chrome后可以认证了，谢谢！
