### ISSUE TITLE
下载文件时有时会下载一个html片段

### ISSUE THREAD

**Issue by panda2134** [robertying/learnX#756]
如图。这个问题在iOS端存在很久了（大概在去年11月的时候就会发生），移植到macOS后依旧存在。
表现为第一次刷新前后都会下载一个数十kb的文件（和正式pdf/ppt没有关系，猜测大概是一个错误界面？），第3/4次刷新后才会下载正确的文件。

可能是 API 的问题，一个可能的workaround是在文件小于100kb时对下载的文件头进行检查，如果不正确就重复下载一定次数。

**Comment by robertying** [comment]
大概是对哪种类型的哪些大小文件会产生这个问题呢？

我这里200k左右的没有遇到过这个问题。

**Comment by panda2134** [comment]
<img width="656" alt="图片" src="https://user-images.githubusercontent.com/7239200/83583917-3873e780-a578-11ea-90be-bf42cb5d4f25.png">

![rec-issue](https://user-images.githubusercontent.com/7239200/83583920-3ca00500-a578-11ea-93c8-d8d33256bfc9.gif)

复现：文件大小1.15M；
最开始背景内Preview.app是另一个文件，所选择的文件下载了3次才下载成功。

**Comment by panda2134** [comment]
<img width="650" alt="图片" src="https://user-images.githubusercontent.com/7239200/83702156-6d4a7200-a63e-11ea-8ddb-ee2edf5afb96.png">
这是某个损坏的文件内容

**Comment by panda2134** [comment]
应该是api处理登录跳转的时候出了问题？
