### ISSUE TITLE
firebase推送作业批改后，作业页面不会自动刷新，要手动刷新才能看到批改结果

### ISSUE THREAD

**Issue by panda2134** [robertying/learnX#757]
应该可以做成收到推送后自动刷新对应条目？

**Comment by robertying** [comment]
现在 iOS 下面，是实现这个功能的……点击推送进入 App 之后，会自动更新那个作业。但是 Android 上那个 API 对“点击通知”这一行为一直没有反应。其他实现也不太好做。

**Comment by robertying** [comment]
所以在 iOS 下也不行吗？

**Comment by panda2134** [comment]
iOS下learnX v10.3.0 时好时坏，有时不会刷新，但是不好复现

发自我的iPhone
