### ISSUE TITLE
非百分制成绩无法正常显示

### ISSUE THREAD

**Issue by fangmaoer** [robertying/learnX#758]
如果老师批改作业的成绩不是百分制，则会显示-100，-99这种

**Comment by robertying** [comment]
请问具体的成绩是什么呢？

**Comment by fangmaoer** [comment]
> 请问具体的成绩是什么呢？

比如如果成绩是“已阅”，会显示成“-100”；如果成绩是“A+”，会显示成“-99”；如果成绩是“A”，会显示成“-98”
