### ISSUE TITLE
安卓最新版闪退

### ISSUE THREAD

**Issue by yangwang2001** [robertying/learnX#766]
10.5.0（v8a）安装后闪退。
此前曾出现过直接升级安装后闪退，不过卸载原app再重新安装即可解决。
最新版安装后登录一次后打开即闪退，重装不管用。
设备是荣耀v20，安卓10。

**Comment by robertying** [comment]
Fixed via 3f5fda7bb5be685d12fc1b206a59b6ac21685ebe
