### ISSUE TITLE
课程文件保存问题

### ISSUE THREAD

**Issue by WXR1998** [robertying/learnX#84]
课程文件无法正常保存到本地
右上角点击分享不能“用其他应用打开”，如pdf查看器等
保存到文件后，文件名不对，也无法打开
环境：iOS 12 ipad和iphone6sp

**Comment by robertying** [comment]
请问设置-关于中的版本是多少呢？我在2.1.1中测试iPad可以正常分享文件到Notability以及iCloud云盘，并能打开。

**Comment by robertying** [comment]
Resolved in v2.1.0
