### ISSUE TITLE
[希望新增] 希望增加对单条作业/公告/文件的忽略功能

### ISSUE THREAD

**Issue by Xiangze-Li** [robertying/learnX#849]
比如老师在作业的正常提交窗口之外又开了迟交窗口，后者就会一直以未完成挂在时间线上，希望可以单条屏蔽掉

**Comment by robertying** [comment]
最近可能会做重构，到时候会考虑加入这个功能。

**Comment by robertying** [comment]
v12 开始支持“归档”功能，可以把不再需要的内容归档，从而从时间线上移除。
