### ISSUE TITLE
iPad OS 日历同步秋季学期课程失败（反复尝试也不行）

### ISSUE THREAD

**Issue by kebamt** [robertying/learnX#868]
如题

**Comment by robertying** [comment]
失败提示是啥？

**Comment by kebamt** [comment]
错误提示：Failed to sync course schedule, try again later or tomorrow.

**Comment by robertying** [comment]
他人测试，是可以的。
请升级到最新版，确保在校园网环境下进行同步。或者等明天再同步。

**Comment by kebamt** [comment]
今天日历同步成功了。
可作业未能同步Reminder。
所使用系统是iPad OS 14 Beta 8，是不是因为Learn X未设配iOS 14 呀？谢谢
还想问一下Learn X下一个版本什么时候发布，很期待，谢谢！

**Comment by robertying** [comment]
iOS 14 也是没问题的。确保现在有未完成的作业。
