### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by kebamt** [robertying/learnX#869]
1.**建议加入Rar格式文件的支持。**
有很多老师用此格式，然而iOS，iPad OS 系统文件管理器不支持此格式，只能下载第三方软件，然而第三方解压缩软件广告频繁，体验极差。
2.**建议提供UI界面个性化功能。**根据自己的喜好调节颜色，布局等等吧。

谢谢！加油

**Comment by robertying** [comment]
RAR 格式不是开放格式，所以一般很少会对其做兼容，因此各个平台上理论上都很少提供自带的解压。其次，解压 RAR 显然超出了 learnX 的范围，所有文件都应该是由第三方应用打开。

定制布局，目前只考虑 tab 栏的顺序修改。其他不好做。
