### ISSUE TITLE
请问有什么办法可以实现日历在电脑端同步

### ISSUE THREAD

**Issue by Zhang-RQ** [robertying/learnX#872]
outlook手机端由于未知原因无法同步
![)A~ R6PBEPR0Q(PRE_{LZDK](https://user-images.githubusercontent.com/30769668/93039838-20cdf400-f67b-11ea-9c5a-c55e347eb656.jpg)
请问有什么方法可以解决该问题

**Comment by robertying** [comment]
现在 learnX 写入的日历没有对任何 Android 内建的日历同步功能进行测试，可能可以用，可能不能用。
其次，我理解这是 Outlook 自己的账户下的日历功能，感觉和 learnX 没什么关系，请问 Outlook 是支持同步本地自己新建的任何日历吗？

**Comment by Zhang-RQ** [comment]
> 现在 learnX 写入的日历没有对任何 Android 内建的日历同步功能进行测试，可能可以用，可能不能用。
> 其次，我理解这是 Outlook 自己的账户下的日历功能，感觉和 learnX 没什么关系，请问 Outlook 是支持同步本地自己新建的任何日历吗？

outlook可以同步除了learnX的本地日历（系统自带的）

**Comment by robertying** [comment]
我猜测和我设置的日历类型有关，到时候下个 Outlook 看一下。

**Comment by kebamt** [comment]
好像是可以把手机端同步的日历数据通过第三方app导出位.ics格式文件，在电脑上导入就可以，亲测成功。（所使用第三方app「安卓」iCalendar import/export)

**Comment by kebamt** [comment]
**好像是可以把手机端同步的日历数据通过第三方app导出位.ics格式文件，在电脑上导入就可以，亲测成功。（所使用第三方app「安卓」iCalendar import/export)**

**Comment by kebamt** [comment]
**好像是可以把手机端同步的日历数据通过第三方app导出位.ics格式文件，在电脑上导入就可以，亲测成功。（所使用第三方app「安卓」iCalendar import/export)**

**Comment by robertying** [comment]
我大概看了一下，Android 中新建日历时需要说明日历所属账号，这个账号应该就是负责同步的账号。但是 learnX 无法和任何一个账户系统关联，设置为了 localAccount。可能是这一原因导致无法被其他应用账号同步。暂时不打算为此做更改。
