### ISSUE TITLE
课程同步至日历似乎有错误

### ISSUE THREAD

**Issue by makui1** [robertying/learnX#873]
![IMG_0693](https://user-images.githubusercontent.com/53214322/93053265-2424a800-f69a-11ea-9917-5f53c8bf9168.png)如图，第一周课程是正确的，但是第二周以及以后
![IMG_0694](https://user-images.githubusercontent.com/53214322/93053387-4e766580-f69a-11ea-9f1a-0124d9c78716.png)呀，咋周日也有课了呀

**Comment by robertying** [comment]
可否尝试一下“删除已同步日历”，再重新同步？

**Comment by makui1** [comment]
你好，试过这种方法，还是由同样的错误

**Comment by robertying** [comment]
麻烦尝试以下步骤：

1. 登录网络学堂
2. 在同一个浏览器访问 https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20200901&p_end_date=20201001&jsoncallback=thu_learn_lib_jsonp_extractor
3. 查看返回结果
4. 建议在抹除敏感信息后，将返回结果附上，或者可以发到我的邮箱中。

**Comment by robertying** [comment]
网络学堂返回结果问题
