### ISSUE TITLE
安卓端后台跳到前台

### ISSUE THREAD

**Issue by yangwang2001** [robertying/learnX#882]
后台运行app时常会很奇怪地跳到前台。
EMUI10.1 AndroidQ
Oneui1.1 AndroidP

**Comment by robertying** [comment]
请问有没有开启推送通知的功能？

**Comment by yangwang2001** [comment]
没有开启推送，开启了作业同步到日程。

**Comment by yangwang2001** [comment]
似乎找到规律了，正在刷新时切换前台应用，刷新完成后learnX就会回到前台。

**Comment by robertying** [comment]
了解。

**Comment by robertying** [comment]
v12 版本删除了可能会导致这一问题的后台刷新功能。请升级到最新版本后检查此问题是否仍然存在，如果继续存在，可以 reopen。
