### ISSUE TITLE
”作业“中，重名文件打开会失败

### ISSUE THREAD

**Issue by sunmy2019** [robertying/learnX#883]
我的”作业“中有重名的文件，会打开错误的文件

我查看了一下，就是文件目录下的 assignments 下面同一个课程中文件的名字都是同一个 dummy，但我有门课，所有作业提交的文件都是 hw.pdf，就导致打开了错误的 hw-dummy.pdf

此外，如果老师更新了作业，也不会更新版本。不知道有没有办法换个版本管理方案

**Comment by robertying** [comment]
v12 开始，文件保存路径会以文件 id 为前缀，应该解决了此问题。
