### ISSUE TITLE
一键已读的功能

### ISSUE THREAD

**Issue by overwenyan** [robertying/learnX#891]
在切换学期时，时间过长就会存在之前读过的消息全都变成了未读状态，感觉在观感上略显麻烦，不知道是否方便设置这样的功能，谢谢开发者！

**Comment by robertying** [comment]
v12 开始支持“归档”功能，可以把不再需要的内容归档。
同时，未读状态现在与网络学堂保持一致。当然，状态不会实时改变，需要重新刷新才可以。
