### ISSUE TITLE
MacOS 11兼容性

### ISSUE THREAD

**Issue by wangziha17** [robertying/learnX#953]
MacOS 11似乎会被识别为移动端系统，原有的左上角刷新键无法显示，变成了和移动端一样的下拉刷新。此外文件从自动跳转pdf阅读器打开变成了APP内打开，不太方便。

**Comment by robertying** [comment]
在写一个新版本，因此目前的版本就搁置了各种修复。但是我最近也没有什么进度，可能需要再等待一下。

**Comment by robertying** [comment]
v12 已经上线，可以等待审核更新。
