### ISSUE TITLE
Android11下无法打开作业附件

### ISSUE THREAD

**Issue by Zhang-RQ** [robertying/learnX#962]
如题，手机系统为MIUI12.2.2(稳定版)
Android版本为11
推测为Android11储存机制改变造成的
https://developer.android.google.cn/about/versions/11/privacy/storage?hl=zh-cn

**Comment by robertying** [comment]
App 使用的是应用内部存储，应该是不存在权限问题的。能否提供打开作业时的情况描述？

**Comment by Zhang-RQ** [comment]
> App 使用的是应用内部存储，应该是不存在权限问题的。能否提供打开作业时的情况描述？

在有“刷新”和“打开”的页面点击“打开”没有任何反应

**Comment by robertying** [comment]
在 MIUI Android 11 上测试了 v12.1.0，应该是没有问题了。如果问题依旧存在，请 reopen。
