### ISSUE TITLE
希望增加一键全部已读功能 以及同步云端已读状态的功能

### ISSUE THREAD

**Issue by Xu1084** [robertying/learnX#971]
发现在电脑端已读的公告或文件，在app上仍显示未读，也没有一键已读的功能，一条条点开又太麻烦，导致未读消息一直积累着几十条。所以希望能新增同步已读状态的功能，或者加一个一键全部已读的功能～

**Comment by robertying** [comment]
下个版本有在做“归档”的功能，可以手动选择部分或全部通知、文件，将其归档，首页可以只看未归档。这样可以避免网络学堂的未读状态的影响。App 和网络学堂的未读状态完全同步，很难很好地实现。

**Comment by robertying** [comment]
v12 开始支持“归档”功能，可以把不再需要的内容归档。
同时，未读状态现在与网络学堂保持一致。当然，状态不会实时改变，需要重新刷新才可以。
