### ISSUE TITLE
安卓端文件相关疑问

### ISSUE THREAD

**Issue by yangwang2001** [robertying/learnX#989]
1. 安卓端“保存到文档”开关起到什么作用呢，开关会有什么影响？（APP并未接入安卓SAF，安卓无法浏览应用内部文档。也没有在Android/data下保存文件。）  
![Screenshot_20210302_212829_io robertying learnx](https://user-images.githubusercontent.com/56078461/109656669-a1d46580-7b9f-11eb-8151-b3cacf57bfe1.jpg)
![Screenshot_20210302_212811_com android documentsui_edit_497779444058418](https://user-images.githubusercontent.com/56078461/109657192-2de68d00-7ba0-11eb-8423-80ca9082def1.jpg)

2. 安卓端使用分享功能分享到mixplorer复制文件，报错如图，但可以正常分享到微信等APP。
![Screenshot_20210302_212043_io robertying learnx](https://user-images.githubusercontent.com/56078461/109657214-35a63180-7ba0-11eb-8638-7c9f52e2a32a.jpg)

**Comment by robertying** [comment]
保存到文档，使得文件会一直占用空间，直到 App 被卸载；默认保存到缓存，这个位置会根据系统自身调度来决定是否需要清理以节约空间。对于文件访问没有区别，因为两者都是在 App 内部存储中，不 root 应该无法访问。

**Comment by robertying** [comment]
涉及到这个文件管理器的话，我怀疑是因为分享的权限问题。因为我没有专门研究过这一点，所以也不太清楚具体原因。
也因为这点，Android 下提供了“分享”和“打开”的功能，分享应该是近年来 Android 才普及能够对标 iOS 分享的一套功能，但是 Android 应用普遍通过 intent 来将某文件在其他 App 中“打开”来实现所谓“分享”功能的。可以尝试一下“打开”是否能够在此文件管理器中生效。

**Comment by yangwang2001** [comment]
好的，谢谢解释。
关于通过分享复制文件的问题，使用“打开”来操作没有出现权限错误。（“分享”到其他APP也未见问题，疑似mixplorer的问题）。
