### ISSUE TITLE
ios 版显示作业提交成功但实际上并未成功

### ISSUE THREAD

**Issue by mmhws** [robertying/learnX#997]

**Comment by robertying** [comment]
需要更多信息？

**Comment by robertying** [comment]
比如版本号，复现方式等等。

**Comment by mmhws** [comment]
> 比如版本号，复现方式等等。

版本号12.3.0，就是目前最新的，复现方式很简单，随便找任何一门课的作业，点击上传附件，点击右上角提交，软件会提示作业提交成功，然而实际上并没有提交成功

**Comment by robertying** [comment]
他人复现并未出现这种情况。

现在只存在可能因为登录过期而导致提交失败的情况，但是这时候软件会直接提示提交失败。

我怀疑你说的这个情况其实已经提交成功，但是你并未手动刷新作业，所以没有看到更新的内容。

我会在每次提交成功后添加自动刷新。

如果你的情况不符合以上几种描述，确定提交作业显示成功，但是网络学堂网站上依旧没有更新，请直接通过邮件与我联系。

**Comment by mmhws** [comment]
并没有登录过期，因为别的功能都正常，并且我很确定没有提交成功，因为电脑网页上也显示未提交。我再试试重新登录吧。

发自我的iPad

**Comment by mmhws** [comment]
重新登录后问题已消失。

发自我的iPad

**Comment by boltma** [comment]
可以复现这个问题，显示“作业提交成功”后，网络学堂上没有更新。重新登录也不解决问题。
